set(output "${BINARY}/limeburg-specs-cli")
file(REMOVE_RECURSE "${output}")
execute_process(COMMAND "${GENERATOR}" "${SOURCE}/metacode/infobank" "${output}"
  RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Specification generation failed: ${stdout}${stderr}")
endif()
file(GLOB specifications "${SOURCE}/limeburg/specs/*.lburg")
foreach(path IN LISTS specifications)
  get_filename_component(name "${path}" NAME)
  file(READ "${path}" expected)
  file(READ "${output}/${name}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "Nonreproducible specification: ${name}")
  endif()
endforeach()
file(APPEND "${output}/riscv64.lburg" "# deliberate freshness regression\n")
file(READ "${output}/riscv64.lburg" before)
execute_process(COMMAND "${GENERATOR}" --check "${SOURCE}/metacode/infobank" "${output}"
  RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
if(result EQUAL 0 OR NOT stderr MATCHES "stale")
  message(FATAL_ERROR "Stale specification was accepted: ${stdout}${stderr}")
endif()
file(READ "${output}/riscv64.lburg" after)
if(NOT after STREQUAL before)
  message(FATAL_ERROR "Freshness checking modified a specification")
endif()
set(invalid "${BINARY}/limeburg-specs-invalid-infobank")
file(REMOVE_RECURSE "${invalid}")
file(MAKE_DIRECTORY "${invalid}/isa")
file(COPY "${SOURCE}/metacode/infobank/isa/nvptx.isa" DESTINATION "${invalid}/isa")
file(READ "${SOURCE}/metacode/infobank/manifest.json" manifest)
string(REPLACE "\"instruction_count\": 42" "\"instruction_count\": 43" manifest "${manifest}")
file(WRITE "${invalid}/manifest.json" "${manifest}")
execute_process(COMMAND "${GENERATOR}" "${invalid}" "${invalid}/output"
  RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
if(result EQUAL 0 OR NOT stderr MATCHES "count mismatch" OR EXISTS "${invalid}/output")
  message(FATAL_ERROR "Mismatched manifest was not rejected transactionally: ${stdout}${stderr}")
endif()
execute_process(COMMAND "${CLI}" --select-burs "${SOURCE}/limeburg/specs/examples/riscv64-addi.limeburg"
  RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
if(NOT result EQUAL 0 OR NOT stdout MATCHES "3: addi" OR NOT stdout MATCHES "cost = 1")
  message(FATAL_ERROR "Infobank BURS example failed: ${stdout}${stderr}")
endif()
