file(WRITE "${BINARY}/machineir-input.traceml" "(add 20 22)")
execute_process(COMMAND "${CLI}" --machineir-json "${BINARY}/machineir-input.traceml" -o "${BINARY}/machineir-input.json" RESULT_VARIABLE status ERROR_VARIABLE error)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "MachineIR exchange production failed: ${error}")
endif()
execute_process(COMMAND "${DC}" -i "-I${SOURCE}/metacode/machine-ir/source" "${SOURCE}/tests/machineir_exchange.d" "-of=${BINARY}/machineir-exchange" RESULT_VARIABLE status ERROR_VARIABLE error)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "D MachineIR exchange build failed: ${error}")
endif()
execute_process(COMMAND "${BACKEND}" "${SOURCE}/tests/fixtures" "${BINARY}" RESULT_VARIABLE status ERROR_VARIABLE error)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "CFG/spill exchange production failed: ${error}")
endif()
execute_process(COMMAND "${BINARY}/machineir-exchange" "${BINARY}/machineir-input.json" "${BINARY}/machineir-returned.json"
  "${BINARY}/machineir-cfg.json" "${BINARY}/machineir-cfg-returned.json" "${BINARY}/machineir-spill.json" "${BINARY}/machineir-spill-returned.json" RESULT_VARIABLE status ERROR_VARIABLE error)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "D MachineIR exchange failed: ${error}")
endif()
execute_process(COMMAND "${BACKEND}" "${SOURCE}/tests/fixtures" "${BINARY}/machineir-cfg-returned.json" "${BINARY}/machineir-spill-returned.json" RESULT_VARIABLE status ERROR_VARIABLE error)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "CFG/spill return encoding failed: ${error}")
endif()
execute_process(COMMAND "${READER}" "${BINARY}/machineir-returned.json" RESULT_VARIABLE status ERROR_VARIABLE error)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "C++ MachineIR return path failed: ${error}")
endif()
