set(work "${BINARY}/objects-interop")
file(MAKE_DIRECTORY "${work}")
execute_process(COMMAND "${OBJECT_TEST}" "${FIXTURES}" "${work}" "${CALLER}" "${HELPER}"
  RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Native object preparation failed: ${output}${error}")
endif()
file(WRITE "${work}/consumer.c" "extern int limestone_object_native(void); int main(void) {return limestone_object_native()==42?0:1;}")
execute_process(COMMAND "${CC}" "${work}/consumer.c" "${work}/native-reemitted.o" "${HELPER}" -o "${work}/consumer"
  RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Native linker rejected reemitted ELF: ${output}${error}")
endif()
execute_process(COMMAND "${work}/consumer" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Native ELF execution failed: ${output}${error}")
endif()
file(WRITE "${work}/source.traceml" "((lambda x (add x 2)) 40)")
execute_process(COMMAND "${CLI}" --target-isa "${FIXTURES}/native-constant.isa" --allocate --encode --object native_entry "${work}/source.traceml" -o "${work}/native.o"
  RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Native TraceML object generation failed: ${output}${error}")
endif()
file(WRITE "${work}/native_consumer.c" "extern long long native_entry(void); int main(void) {return native_entry()==42?0:1;}")
execute_process(COMMAND "${CC}" "${work}/native_consumer.c" "${work}/native.o" -o "${work}/native_consumer"
  RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Native linker rejected TraceML ELF: ${output}${error}")
endif()
execute_process(COMMAND "${work}/native_consumer" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Native TraceML ELF execution failed: ${output}${error}")
endif()
