set(work "${BINARY}/objects-cli")
file(MAKE_DIRECTORY "${work}")
file(WRITE "${work}/graph.umd" "machine unused {} program graph {node %1=const(42):i64;node %2=return(%1) produces_value false properties {control_flow=return;};}")
function(run)
  execute_process(COMMAND "${CLI}" ${ARGV} RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT status EQUAL 0)
    message(FATAL_ERROR "Object CLI failed: ${ARGV}: ${output}${error}")
  endif()
endfunction()
run(--compile-umd --target-isa "${FIXTURES}/backend-machine.isa" --allocate --encode "${work}/graph.umd" -o "${work}/code.bin")
run(--compile-umd --target-isa "${FIXTURES}/backend-machine.isa" --allocate --encode --object entry "${work}/graph.umd" -o "${work}/code.o")
execute_process(COMMAND "${CLI}" --inspect-object "${work}/code.o" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT status EQUAL 0 OR NOT output MATCHES "machine 65534" OR NOT output MATCHES "symbol 0 entry section 0")
  message(FATAL_ERROR "Object inspection failed: ${output}${error}")
endif()
run(--link-objects "${FIXTURES}/backend-machine.isa" --input-object "${work}/code.o" -o "${work}/linked.bin")
file(SHA256 "${work}/code.bin" original)
file(SHA256 "${work}/linked.bin" linked)
if(NOT original STREQUAL linked)
  message(FATAL_ERROR "Linked pipeline bytes changed")
endif()
run(--wrap-object "${FIXTURES}/backend-machine.isa" wrapped "${work}/code.bin" -o "${work}/wrapped.o")
run(--link-objects "${FIXTURES}/backend-machine.isa" "${work}/wrapped.o" -o "${work}/rewrapped.bin")
file(SHA256 "${work}/rewrapped.bin" wrapped)
if(NOT original STREQUAL wrapped)
  message(FATAL_ERROR "Raw code object roundtrip changed bytes")
endif()
run(--wrap-object "${FIXTURES}/object-i386.isa" entry32 "${work}/code.bin" -o "${work}/wrapped32.o")
execute_process(COMMAND "${CLI}" --inspect-object "${work}/wrapped32.o" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT status EQUAL 0 OR NOT output MATCHES "ELF32 machine 3")
  message(FATAL_ERROR "ELF32 inspection failed: ${output}${error}")
endif()
run(--link-objects "${FIXTURES}/object-i386.isa" "${work}/wrapped32.o" -o "${work}/rewrapped32.bin")
file(SHA256 "${work}/rewrapped32.bin" wrapped32)
if(NOT original STREQUAL wrapped32)
  message(FATAL_ERROR "ELF32 raw object roundtrip changed bytes")
endif()
foreach(mode IN ITEMS --inspect-object --object)
  execute_process(COMMAND "${CLI}" "${mode}" "${work}/graph.umd" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(status EQUAL 0)
    message(FATAL_ERROR "Invalid object CLI arguments accepted: ${mode}")
  endif()
endforeach()
file(WRITE "${work}/source.traceml" "((lambda x (add x 2)) 40)")
run(--target-isa "${FIXTURES}/native-constant.isa" --allocate --encode --object native_entry "${work}/source.traceml" -o "${work}/native.o")
run(--link-objects "${FIXTURES}/native-constant.isa" "${work}/native.o" -o "${work}/native.bin")
file(READ "${work}/native.bin" native HEX)
if(NOT native STREQUAL "48c7c02a000000c3")
  message(FATAL_ERROR "Native TraceML encoding incorrect: ${native}")
endif()
