#include "test.hpp"
#include "schedrow.hpp"
#include "schedrow/motion.hpp"
#include <map>

int main(){return test_main([]{
  using namespace limestone;
  using namespace schedrow;
  Region region{"ports"};
  for(uint32_t id=1;id<=3;++id){Instruction i{};i.id=id;i.opcode="op";i.resources={{"ALU",3,0.5}};region.instructions.push_back(i);}
  MachineModel model{{{"ALU",1}},2};auto scheduled=take(schedule(region,model));
  CHECK(scheduled[0].cycle==0&&scheduled[1].cycle==0&&scheduled[2].cycle==3);take(verify(region,model,scheduled));
  auto invalid=scheduled;invalid[2].cycle=1;fails(verify(region,model,invalid),Error::Code::Conflict);
  auto impossible=region;impossible.instructions[0].resources={{"ALU",1,0.7},{"ALU",1,0.7}};fails(schedule(impossible,model),Error::Code::Unsatisfiable);
  auto unknown=region;unknown.instructions[0].resources[0].resource="missing";fails(schedule(unknown,model),Error::Code::InvalidArgument);
  auto nan=region;nan.instructions[0].resources[0].quantity=std::numeric_limits<double>::quiet_NaN();fails(schedule(nan,model),Error::Code::InvalidArgument);
  Region alternatives{"alternatives"};Instruction flexible{};flexible.id=1;flexible.resources={{"",1,1,0,{"A","B"}}};
  Instruction fixed{};fixed.id=2;fixed.resources={{"A",1,1}};alternatives.instructions={flexible,fixed};
  MachineModel ports{{{"A",1},{"B",1}},2};std::vector<Scheduled> together{{1,0},{2,0}};take(verify(alternatives,ports,together));
  take(verify(alternatives,ports,take(schedule(alternatives,ports))));
  Region hazards{"hazards"};Instruction write{};write.id=10;write.defs={1};write.latency=3;
  Instruction read{};read.id=2;read.uses={1};Instruction overwrite{};overwrite.id=3;overwrite.defs={1};
  hazards.instructions={write,read,overwrite};auto augmented=take(dependencies(hazards));
  CHECK(augmented.deps.size()==3);
  CHECK(std::any_of(augmented.deps.begin(),augmented.deps.end(),[](auto& d){return d.producer==10&&d.consumer==2&&d.kind==DepKind::True&&d.latency==3&&!d.scheduler_only;}));
  auto hs=take(schedule(hazards,{}));CHECK(hs[0].id==10&&hs[1].cycle>=3);take(verify(hazards,{},hs));
  auto late_first=hs;std::swap(late_first[0],late_first[1]);fails(verify(hazards,{},late_first),Error::Code::Conflict);
  Region barrier{"barrier"};Instruction before{};before.id=4;Instruction fence{};fence.id=5;fence.barrier=true;Instruction after{};after.id=6;
  barrier.instructions={before,fence,after};auto fenced=take(dependencies(barrier));CHECK(fenced.deps.size()==2);CHECK(fenced.deps[0].scheduler_only);
  auto cycle=hazards;cycle.deps={{10,2,DepKind::Control,0},{2,10,DepKind::Control,0}};
  fails(schedule(cycle,{}),Error::Code::Conflict);fails(verify(cycle,{},std::vector<Scheduled>{{10,0},{2,0},{3,0}}),Error::Code::Conflict);
  auto loop=hazards;loop.deps={{10,2,DepKind::True,1,1}};fails(schedule(loop,{}),Error::Code::Unsupported);
  auto forged=hs;forged[0].id=99;fails(verify(hazards,{},forged),Error::Code::Conflict);
  Region mixed{"mixed-slots"};flexible.resources.clear();fixed.resources.clear();fixed.issue_slots={0};mixed.instructions={flexible,fixed};MachineModel dual{{},2};
  auto slots=take(schedule(mixed,dual));CHECK(slots[0].cycle==0&&slots[1].cycle==0);take(verify(mixed,dual,slots));
  fails(verify(mixed,dual,std::vector<Scheduled>{{flexible.id,0,0},{fixed.id,0,0}}),Error::Code::Conflict);
  Region ordering{"memory-fence"};before.access=MemoryAccess{true,false};fence.barrier=false;fence.access=MemoryAccess{};fence.access->ordering=MemoryOrdering::Sequential;after.access=MemoryAccess{true,false};ordering.instructions={before,fence,after};CHECK(take(dependencies(ordering)).deps.size()==2);
  Region atomic_reads{"atomic-read-coherence"};
  Instruction atomic_first{};atomic_first.id=70;atomic_first.latency=0;atomic_first.access=MemoryAccess{true,false,false,true,MemoryOrdering::Relaxed,"heap",{4}};
  auto atomic_second=atomic_first;atomic_second.id=20;atomic_second.priority=100;
  atomic_reads.instructions={atomic_first,atomic_second};
  auto coherent=take(dependencies(atomic_reads));
  CHECK(coherent.deps.size()==1&&coherent.deps[0].producer==70&&coherent.deps[0].consumer==20&&coherent.deps[0].kind==DepKind::Memory&&!coherent.deps[0].scheduler_only);
  auto coherent_schedule=take(schedule(atomic_reads,dual));
  CHECK(coherent_schedule[0].id==70&&coherent_schedule[1].id==20);
  take(verify(atomic_reads,dual,coherent_schedule));
  fails(verify_order(atomic_reads,std::vector<uint32_t>{20,70}),Error::Code::Conflict);
  fails(verify(atomic_reads,dual,std::vector<Scheduled>{{20,0},{70,0}}),Error::Code::Conflict);
  auto coherent_loop=take(schedule_modulo(atomic_reads,dual,{1,4,1000}));
  CHECK(coherent_loop[0].id==70&&coherent_loop[1].id==20);
  fails(verify_modulo(atomic_reads,dual,std::vector<Scheduled>{{20,0},{70,0}},1),Error::Code::Conflict);
  auto independent_reads=atomic_reads;independent_reads.instructions[1].access->alias_sets={5};
  CHECK(take(dependencies(independent_reads)).deps.empty());
  CHECK(take(schedule(independent_reads,dual))[0].id==20);
  independent_reads.instructions[1].access->alias_sets.clear();
  CHECK(take(dependencies(independent_reads)).deps.size()==1);
  independent_reads=atomic_reads;independent_reads.instructions[1].access->address_space="private";
  CHECK(take(dependencies(independent_reads)).deps.empty());
  independent_reads=atomic_reads;for(auto& instruction:independent_reads.instructions)instruction.access->atomic=false;
  CHECK(take(dependencies(independent_reads)).deps.empty());
  Region separate{"latency-domains"};write.latency=4;write.implicit_defs={1};write.result_latency={{1,0}};read.implicit_uses={1};separate.instructions={write,read};auto timing=take(schedule(separate,{}));CHECK(timing[1].cycle==4);separate.instructions[0].implicit_result_latency={{1,2}};timing=take(schedule(separate,{}));CHECK(timing[1].cycle==2);take(verify(separate,{},timing));
  separate.instructions[0].implicit_result_latency={{99,2}};fails(schedule(separate,{}),Error::Code::Conflict);
  Region ranged{"bounded-timing"};Instruction producer{};producer.id=10;producer.opcode="MUL";producer.defs={7};producer.implicit_defs={7};producer.latency_range=LatencyRange{2,8};producer.result_latency_ranges={{7,{2,6}}};producer.implicit_result_latency_ranges={{7,{1,4}}};
  Instruction consumer{};consumer.id=20;consumer.opcode="BR";consumer.uses={7};consumer.implicit_uses={7};producer.operand_latencies={{7,"BR",0,{0,2},false},{7,"BR",0,{1,3},true}};ranged.instructions={producer,consumer};
  auto bounds=take(dependencies(ranged));CHECK(bounds.deps.size()==1&&bounds.deps[0].latency==3&&bounds.deps[0].latency_range==LatencyRange({1,3}));auto ranged_schedule=take(schedule(ranged,{}));CHECK(ranged_schedule[1].cycle==3);take(verify(ranged,{},ranged_schedule));
  ranged_schedule[1].cycle=2;fails(verify(ranged,{},ranged_schedule),Error::Code::Conflict);fails(verify_modulo(ranged,{},ranged_schedule,10),Error::Code::Conflict);
  ranged.instructions[1].opcode="OTHER";CHECK(take(schedule(ranged,{}))[1].cycle==6);ranged.instructions[1].uses.clear();CHECK(take(schedule(ranged,{}))[1].cycle==4);
  auto bad_range=ranged;bad_range.instructions[0].latency_range=LatencyRange{9,8};fails(schedule(bad_range,{}),Error::Code::InvalidArgument);bad_range=ranged;bad_range.instructions[0].operand_latencies.push_back(producer.operand_latencies[0]);fails(schedule(bad_range,{}),Error::Code::Conflict);
  Region ranged_loop{"ranged-recurrence"};consumer.uses.clear();consumer.implicit_uses.clear();ranged_loop.instructions={consumer};ranged_loop.deps={{20,20,DepKind::True,0,1,false,LatencyRange{1,5}}};fails(schedule_modulo(ranged_loop,{}, {4,8,100}),Error::Code::Unsatisfiable);take(verify_modulo(ranged_loop,{},take(schedule_modulo(ranged_loop,{}, {5,8,100})),5));
  Region memory_timing{"memory-completion"};Instruction store{};store.id=1;store.memory=true;store.access=MemoryAccess{false,true};store.memory_latency=LatencyRange{2,7};Instruction load{};load.id=2;load.memory=true;load.access=MemoryAccess{true,false};memory_timing.instructions={store,load};auto memory_schedule=take(schedule(memory_timing,{}));CHECK(memory_schedule[1].cycle==7);take(verify(memory_timing,{},memory_schedule));memory_timing.instructions[0].access->alias_sets={1};memory_timing.instructions[1].access->alias_sets={2};CHECK(take(dependencies(memory_timing)).deps.empty());
  Region emission{"zero-latency-order"};Instruction a{};a.id=1;a.defs={7};a.latency=0;Instruction b{};b.id=2;b.uses={7};emission.instructions={a,b};const std::vector<uint32_t> legal_order{1,2},reverse_order{2,1};take(verify_order(emission,legal_order));fails(verify_order(emission,reverse_order),Error::Code::Conflict);
  take(verify(emission,dual,std::vector<Scheduled>{{1,0},{2,0}}));fails(verify(emission,dual,std::vector<Scheduled>{{2,0},{1,0}}),Error::Code::Conflict);
  take(verify_modulo(emission,dual,std::vector<Scheduled>{{1,0},{2,0}},1));fails(verify_modulo(emission,dual,std::vector<Scheduled>{{2,0},{1,0}},1),Error::Code::Conflict);
  Region recurrence{"loop-distance"};recurrence.instructions={a,b};recurrence.instructions[0].defs.clear();recurrence.instructions[1].uses.clear();recurrence.deps={{2,1,DepKind::True,1,1}};take(verify_modulo(recurrence,dual,std::vector<Scheduled>{{1,0},{2,0}},1));
  Region bundle{"joint-bundle"};Instruction first{},second{};first.id=8;first.latency=0;first.resources={{"",1,1,0,{"A","B"}}};second.id=2;second.latency=0;second.resources={{"A",1,1}};second.issue_slots={0};bundle.instructions={first,second};bundle.groups={{44,GroupKind::Bundle,{8,2},"dual"}};bundle.groups[0].issue_width=2;bundle.groups[0].issue_slots={0,1};
  auto packed=take(schedule(bundle,ports));CHECK(packed[0].id==8&&packed[1].id==2&&packed[0].cycle==packed[1].cycle);CHECK(packed[0].slot==1&&packed[1].slot==0&&packed[0].resources==std::vector<std::string>{"B"});take(verify(bundle,ports,packed));take(verify_order(bundle,std::vector<uint32_t>{8,2}));
  auto bad_bundle=bundle;bad_bundle.instructions[0].issue_slots={0};fails(schedule(bad_bundle,ports),Error::Code::Unsatisfiable);bad_bundle=bundle;bad_bundle.instructions[0].resources={{"A",1,1}};fails(schedule(bad_bundle,ports),Error::Code::Unsatisfiable);fails(schedule(bundle,MachineModel{{{"A",1},{"B",1}},1}),Error::Code::InvalidArgument);
  auto unbundled=bundle;unbundled.groups[0].issue_slots.clear();unbundled.groups[0].issue_width=1;fails(schedule(unbundled,ports),Error::Code::Unsatisfiable);
  bad_bundle=bundle;bad_bundle.instructions[0].defs={7};bad_bundle.instructions[0].latency=1;bad_bundle.instructions[1].uses={7};fails(schedule(bad_bundle,ports),Error::Code::Unsatisfiable);
  auto forged_bundle=packed;forged_bundle[1].cycle=2;fails(verify(bundle,ports,forged_bundle),Error::Code::Conflict);forged_bundle=packed;std::reverse(forged_bundle.begin(),forged_bundle.end());fails(verify(bundle,ports,forged_bundle),Error::Code::Conflict);
  bundle.deps={{8,8,DepKind::True,2,1}};auto periodic=take(schedule_modulo(bundle,ports,{2,4,10000}));CHECK(periodic[0].cycle==periodic[1].cycle&&periodic[0].slot==1);take(verify_modulo(bundle,ports,periodic,2));fails(schedule_modulo(bundle,ports,{1,4,10000}),Error::Code::Unsatisfiable);auto forged_periodic=periodic;forged_periodic[1].cycle+=2;fails(verify_modulo(bundle,ports,forged_periodic,2),Error::Code::Conflict);bundle.deps.clear();
  Region adjacent{"atomic-emission"};a.id=30;a.latency=4;a.defs={7};b.id=99;b.uses={7};Instruction middle{};middle.id=4;middle.priority=50;adjacent.instructions={a,middle,b};adjacent.groups={{5,GroupKind::Fusion,{30,99},"pair","fixture","produce-consume",100}};
  auto contiguous=take(schedule(adjacent,dual));CHECK(contiguous[0].id==30&&contiguous[1].id==99&&contiguous[2].id==4&&contiguous[1].cycle==4);take(verify(adjacent,dual,contiguous));fails(verify_order(adjacent,std::vector<uint32_t>{30,4,99}),Error::Code::Conflict);fails(verify(adjacent,dual,std::vector<Scheduled>{{30,0},{4,2},{99,4}}),Error::Code::Conflict);
  for(auto kind:{GroupKind::Adjacent,GroupKind::Atomic,GroupKind::Pair}){auto unit=adjacent;unit.groups[0].kind=kind;take(verify(unit,dual,take(schedule(unit,dual))));}
  auto ordered=adjacent;ordered.groups[0].kind=GroupKind::Ordered;take(verify(ordered,dual,std::vector<Scheduled>{{30,0},{4,2},{99,4}}));take(verify_order(ordered,std::vector<uint32_t>{30,4,99}));
  auto interleaved=adjacent;interleaved.deps={{30,4,DepKind::Ordering,0},{4,99,DepKind::Ordering,0}};fails(schedule(interleaved,dual),Error::Code::Unsatisfiable);
  auto same_cycle=interleaved;same_cycle.groups[0].kind=GroupKind::SameCycle;same_cycle.instructions[0].latency=0;MachineModel triple{{},3};auto coissued=take(schedule(same_cycle,triple));CHECK(coissued[0].id==30&&coissued[1].id==4&&coissued[2].id==99&&coissued[0].cycle==coissued[2].cycle);take(verify(same_cycle,triple,coissued));take(verify_modulo(same_cycle,triple,take(schedule_modulo(same_cycle,triple,{1,4,10000})),1));fails(schedule(same_cycle,dual),Error::Code::Unsatisfiable);same_cycle.deps[0].latency=1;fails(schedule(same_cycle,triple),Error::Code::Unsatisfiable);
  auto malformed=adjacent;malformed.groups[0].members.push_back(99);fails(schedule(malformed,dual),Error::Code::InvalidArgument);malformed=adjacent;malformed.groups.push_back({6,GroupKind::Adjacent,{4,99}});fails(schedule(malformed,dual),Error::Code::Unsatisfiable);
  Region overlapping{"overlapping"};
  for(uint32_t identity=1;identity<=4;++identity){Instruction instruction{};instruction.id=identity;instruction.latency=0;overlapping.instructions.push_back(instruction);}
  overlapping.groups={{1,GroupKind::Adjacent,{1,2}},{2,GroupKind::Atomic,{2,3}}};
  overlapping.deps={{1,2,DepKind::True,4}};
  auto shared=take(schedule(overlapping,triple));CHECK(shared[0].id==1&&shared[1].id==2&&shared[2].id==3&&shared[1].cycle==4);take(verify(overlapping,triple,shared));
  overlapping.groups={{1,GroupKind::Adjacent,{1,2,3}},{2,GroupKind::SameCycle,{2,4}}};
  shared=take(schedule(overlapping,triple));CHECK(shared[0].cycle==0&&shared[1].cycle==4&&shared[2].cycle==4&&shared[3].cycle==4);take(verify(overlapping,triple,shared));
  fails(schedule(overlapping,dual),Error::Code::Unsatisfiable);
  overlapping.deps.clear();overlapping.instructions.pop_back();overlapping.groups={{1,GroupKind::SameCycle,{1,2}},{2,GroupKind::SameCycle,{2,3}}};
  shared=take(schedule(overlapping,triple));CHECK(shared.size()==3&&shared[0].cycle==shared[2].cycle);take(verify(overlapping,triple,shared));
  auto overlap_modulo=take(schedule_modulo(overlapping,triple,{1,4,10000}));take(verify_modulo(overlapping,triple,overlap_modulo,1));
  auto wrong_overlap=shared;wrong_overlap[2].cycle=1;fails(verify(overlapping,triple,wrong_overlap),Error::Code::Conflict);
  overlapping.deps={{1,3,DepKind::True,1}};fails(schedule(overlapping,triple),Error::Code::Unsatisfiable);overlapping.deps.clear();
  overlapping.instructions[0].issue_slots={0};overlapping.instructions[2].issue_slots={0};fails(schedule(overlapping,triple),Error::Code::Unsatisfiable);
  overlapping.instructions[0].issue_slots.clear();overlapping.instructions[2].issue_slots.clear();
  auto limited=triple;limited.group_search_limit=0;fails(schedule(overlapping,limited),Error::Code::ResourceLimit);limited.group_search_limit=5;fails(schedule(overlapping,limited),Error::Code::ResourceLimit);
  limited.group_search_limit=0;take(verify(overlapping,limited,shared));take(verify_modulo(overlapping,limited,overlap_modulo,1));
  limited.group_search_limit=32;limited.issue_width=UINT32_MAX;fails(schedule(overlapping,limited),Error::Code::ResourceLimit);
  limited.issue_width=3;limited.resource_capacity["bounded"]=1;auto long_reservation=overlapping;long_reservation.instructions[0].resources={{"bounded",UINT32_MAX,1}};fails(schedule(long_reservation,limited),Error::Code::ResourceLimit);
  overlapping.instructions[1].priority=-100;Instruction unrelated{};unrelated.id=4;unrelated.latency=0;overlapping.instructions.push_back(unrelated);
  shared=take(schedule(overlapping,triple));take(verify(overlapping,triple,shared));CHECK(shared[0].id==1&&shared[1].id==2&&shared[2].id==3&&shared[3].id==4);
  overlapping.blocks={{1,"entry",{2}},{2,"exit"}};overlapping.entry=1;for(auto& instruction:overlapping.instructions)instruction.block=instruction.id==4?2:1;
  take(verify_cfg(overlapping,triple,take(schedule_cfg(overlapping,triple))));
  auto overlapping_bundle=bundle;overlapping_bundle.groups.push_back({45,GroupKind::Pair,{8,2}});take(verify(overlapping_bundle,ports,take(schedule(overlapping_bundle,ports))));
  for(auto first_kind:{GroupKind::Adjacent,GroupKind::SameCycle,GroupKind::Bundle})for(auto second_kind:{GroupKind::Adjacent,GroupKind::SameCycle,GroupKind::Bundle})for(uint32_t width=1;width<=3;++width)for(uint32_t mask=0;mask<4;++mask) {
    Region probe{"exhaustive-overlap"};for(uint32_t identity=1;identity<=3;++identity){Instruction instruction{};instruction.id=identity;instruction.latency=0;probe.instructions.push_back(instruction);}
    probe.groups={{1,first_kind,{1,3}},{2,second_kind,{1,2}}};
    if(mask&1)probe.deps.push_back({1,2,DepKind::True,1});if(mask&2)probe.deps.push_back({2,3,DepKind::True,1});
    MachineModel capacity{{},width};bool feasible=false;std::vector<uint32_t> permutation{1,2,3};
    do {for(uint32_t second_cycle=0;second_cycle<=2&&!feasible;++second_cycle)for(uint32_t third_cycle=second_cycle;third_cycle<=2&&!feasible;++third_cycle)feasible=bool(verify(probe,capacity,std::vector<Scheduled>{{permutation[0],0},{permutation[1],second_cycle},{permutation[2],third_cycle}}));}while(!feasible&&std::next_permutation(permutation.begin(),permutation.end()));
    auto result=schedule(probe,capacity);CHECK(bool(result)==feasible);if(result)take(verify(probe,capacity,result.value()));else CHECK(result.error().code==Error::Code::Unsatisfiable);
  }
  auto blocks=bundle;blocks.blocks={{7,"entry",{9}},{9,"exit"}};blocks.entry=7;for(auto& i:blocks.instructions)i.block=7;middle.block=9;blocks.instructions.push_back(middle);auto cfg_schedule=take(schedule_cfg(blocks,ports));take(verify_cfg(blocks,ports,cfg_schedule));
  auto mixed_blocks=cfg_schedule;std::swap(mixed_blocks[1],mixed_blocks[2]);fails(verify_cfg(blocks,ports,mixed_blocks),Error::Code::Conflict);
  auto reversed_blocks=cfg_schedule;std::rotate(reversed_blocks.begin(),reversed_blocks.end()-1,reversed_blocks.end());fails(verify(blocks,ports,reversed_blocks),Error::Code::Conflict);
  fails(schedule_modulo(blocks,ports),Error::Code::Unsupported);
  blocks.groups[0].members={8,4};fails(schedule_cfg(blocks,ports),Error::Code::Unsupported);
  Region wide{"multi-slot"};Instruction wide_op{};wide_op.id=1;wide_op.issue_width=2;wide_op.issue_slots={0,2};Instruction narrow_op{};narrow_op.id=2;narrow_op.issue_slots={1};wide.instructions={wide_op,narrow_op};
  auto wide_schedule=take(schedule(wide,triple));CHECK(wide_schedule[0].cycle==0&&wide_schedule[1].cycle==0);CHECK(wide_schedule[0].slot==0&&wide_schedule[0].additional_slots==std::vector<uint32_t>{2});take(verify(wide,triple,wide_schedule));
  auto wide_invalid=wide_schedule;wide_invalid[0].additional_slots={1};fails(verify(wide,triple,wide_invalid),Error::Code::Conflict);wide_invalid=wide_schedule;wide_invalid[0].additional_slots.clear();fails(verify(wide,triple,wide_invalid),Error::Code::Conflict);
  wide.groups={{1,GroupKind::Bundle,{1,2}}};take(verify(wide,triple,take(schedule(wide,triple))));take(verify_modulo(wide,triple,take(schedule_modulo(wide,triple,{1,4,10000})),1));fails(schedule(wide,dual),Error::Code::InvalidArgument);
  wide.instructions[0].issue_slots={0,1};wide.instructions[1].issue_slots={0};fails(schedule(wide,triple),Error::Code::Unsatisfiable);
  MachineModel bounded_machine{{},UINT32_MAX};bounded_machine.group_search_limit=100;
  Region enormous{"bounded-cardinality"};wide_op.issue_slots.clear();wide_op.issue_width=UINT32_MAX;enormous.instructions={wide_op};fails(schedule(enormous,bounded_machine),Error::Code::ResourceLimit);
  enormous.instructions[0].issue_width=1;auto small=take(schedule(enormous,bounded_machine));CHECK(small[0].slot==0);take(verify(enormous,bounded_machine,small));
  bounded_machine.group_search_limit=0;fails(schedule(enormous,bounded_machine),Error::Code::ResourceLimit);take(verify(enormous,bounded_machine,small));
  bounded_machine.verification_limit=0;fails(verify(enormous,bounded_machine,small),Error::Code::ResourceLimit);
  auto prolonged=enormous;prolonged.instructions[0].resources={{"R",UINT32_MAX,1}};MachineModel bounded_resource{{{"R",1}},1};bounded_resource.group_search_limit=100;
  fails(schedule(prolonged,bounded_resource),Error::Code::ResourceLimit);fails(schedule_modulo(prolonged,bounded_resource,{UINT32_MAX,1,100}),Error::Code::ResourceLimit);
  Region diamond{"motion"};diamond.blocks={{0,"entry",{2,1}},{1,"right"},{2,"left",{}, {2}}};
  Instruction input{},branch{},calculation{},left_return{},right_return{};
  input.id=10;input.opcode="INPUT";input.defs={1};
  branch.id=11;branch.opcode="BRANCH";branch.uses={1};branch.terminator=true;branch.control=ControlFlow::ConditionalBranch;branch.block_targets={2,1};
  calculation.id=12;calculation.opcode="DOUBLE";calculation.defs={2};calculation.uses={1};calculation.block=2;calculation.origin="motion:8:4";
  left_return.id=13;left_return.opcode="RETURN";left_return.uses={2};left_return.block=2;left_return.terminator=true;left_return.control=ControlFlow::Return;
  right_return=left_return;right_return.id=14;right_return.uses={1};right_return.block=1;
  diamond.instructions={input,branch,right_return,calculation,left_return};take(verify_ssa(diamond));
  auto hoisted=take(move_instruction(diamond,{12,0}));CHECK(hoisted.instructions[1].id==12&&hoisted.instructions[1].origin=="motion:8:4");take(verify_cfg(hoisted,dual,take(schedule_cfg(hoisted,dual))));
  auto sunk=take(move_instruction(hoisted,{12,2,13}));take(verify_cfg(sunk,dual,take(schedule_cfg(sunk,dual))));CHECK(sunk.instructions[3].id==12);
  auto run=[](const Region& region,int64_t argument){std::map<uint32_t,int64_t> values;uint32_t block=region.entry;for(size_t budget=0;budget<8;++budget){for(auto& instruction:region.instructions)if(instruction.block==block){if(instruction.opcode=="INPUT")values[1]=argument;else if(instruction.opcode=="DOUBLE")values[2]=2*values.at(1);else if(instruction.opcode=="BRANCH"){block=values.at(1)?2:1;break;}else if(instruction.opcode=="RETURN")return values.at(instruction.uses[0]);}}throw std::runtime_error("motion execution did not return");};
  for(auto value:{0,1,21,-8})CHECK(run(diamond,value)==run(hoisted,value)&&run(diamond,value)==run(sunk,value));
  fails(move_instruction(diamond,{12,1}),Error::Code::Conflict);fails(move_instruction(diamond,{12,0,10}),Error::Code::Conflict);fails(move_instruction(diamond,{11,2}),Error::Code::Unsupported);fails(move_instruction(diamond,{12,0,13}),Error::Code::InvalidArgument);
  auto pinned_motion=diamond;pinned_motion.instructions[3].may_trap=true;fails(move_instruction(pinned_motion,{12,0}),Error::Code::Unsupported);
  MotionOptions proof;proof.prove=[](const auto&,const auto&){return Result<bool>::ok(false);};fails(move_instruction(pinned_motion,{12,0},proof),Error::Code::Conflict);
  proof.prove=[](const auto&,const auto&){return Result<bool>::ok(true);};take(move_instruction(pinned_motion,{12,0},proof));
  pinned_motion=diamond;pinned_motion.groups={{1,GroupKind::Pair,{12,13}}};fails(move_instruction(pinned_motion,{12,0}),Error::Code::Conflict);
  MotionOptions no_work;no_work.work_limit=0;fails(move_instruction(diamond,{12,0},no_work),Error::Code::ResourceLimit);
  auto duplicate_ssa=diamond;duplicate_ssa.instructions[3].defs={1};fails(verify_ssa(duplicate_ssa),Error::Code::Conflict);
});}
