foreach(pair IN ITEMS "--select-burs|selection.limeburg|ADDI" "--select-burs|selection-includes.limeburg|ADDI" "--analyze-burs|selection-includes.limeburg|via rule 3 -> ADDI" "--compile-umd|arithmetic-includes.umd|ADD" "--schedule-il|scheduling.schedrow|cycle 2" "--schedule-il|grouping.schedrow|resource B" "--allocate-il|allocation.regtl|v8 -> physical 2")
  string(REPLACE "|" ";" args "${pair}")
  list(GET args 0 mode)
  list(GET args 1 file)
  list(GET args 2 expected)
  execute_process(COMMAND "${CLI}" "${mode}" "${FIXTURES}/${file}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT status EQUAL 0 OR NOT output MATCHES "${expected}")
    message(FATAL_ERROR "Text IL CLI failed for ${mode}: ${error}\n${output}")
  endif()
endforeach()
execute_process(COMMAND "${CLI}" --allocate-il --allocator pbqp "${FIXTURES}/allocation-costs.regtl"
  RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT status EQUAL 0 OR NOT output MATCHES "v1 -> physical 0" OR NOT output MATCHES "v2 -> spill")
  message(FATAL_ERROR "PBQP CLI failed: ${error}\n${output}")
endif()
