#include "test.hpp"
#include "limeburg/text.hpp"
#include "schedrow/text.hpp"
#include "regtl/text.hpp"
#include <fstream>

static std::string read(const std::string& path){std::ifstream f(path);CHECK(f.good());return {(std::istreambuf_iterator<char>(f)),{}};}
int main(int argc,char** argv){return test_main([&]{
  using namespace limestone;CHECK(argc==2);const std::string fixtures=argv[1];
  auto burs=take(limeburg::load_rules(read(fixtures+"/selection.limeburg")));auto& tree=burs.trees[0];auto selected=take(limeburg::select(tree.nodes,tree.root,burs.rules,tree.nonterminal));auto emitted=take(limeburg::emit_scheduler(tree.nodes,burs.rules,selected));CHECK(selected.cost==3&&emitted.instructions.size()==2&&emitted.instructions[1].opcode=="ADDI"&&emitted.instructions[1].immediates[0].second==7);
  auto rules_text=take(limeburg::print_rules(burs));auto copied=take(limeburg::load_rules(rules_text));CHECK(take(limeburg::print_rules(copied))==rules_text);CHECK(take(limeburg::select(copied.trees[0].nodes,copied.trees[0].root,copied.rules,"reg")).cost==3);
  fails(limeburg::load_rules("ruleset x {nonterminal reg;terminal A(1);rule reg: A() -> X;}"),Error::Code::InvalidArgument);
  fails(limeburg::load_rules("ruleset x {nonterminal reg;rule reg: UNKNOWN() -> X;}"),Error::Code::NotFound);
  fails(limeburg::load_rules("include \"missing\";"),Error::Code::Unsupported);
  auto included=take(limeburg::load_rules_file(fixtures+"/selection-includes.limeburg"));CHECK(included.rules.rules.size()==3&&included.trees[0].nodes[0].origin.ends_with("/includes/sum.tree:2"));auto& included_tree=included.trees[0];auto included_selection=take(limeburg::select(included_tree.nodes,included_tree.root,included.rules,"reg"));CHECK(included_selection.cost==3&&take(limeburg::emit_scheduler(included_tree.nodes,included.rules,included_selection)).instructions.back().opcode=="ADDI");auto included_text=take(limeburg::print_rules(included));CHECK(take(limeburg::print_rules(take(limeburg::load_rules(included_text))))==included_text);
  CHECK(take(limeburg::emit_scheduler(included_tree.nodes,included.rules,included_selection)).instructions.back().origin.find("/includes/scalar.rules:4:1")!=std::string::npos);
  syntax::IncludeOptions options;options.resolver=[](auto,auto){return Result<syntax::ResolvedSource>::ok({"virtual.rules","terminal A(0);\nterminal A(0);"});};auto duplicate=limeburg::load_rules("ruleset x {include \"rules\";}","root.rules",options);fails(duplicate,Error::Code::Conflict);CHECK(duplicate.error().message.find("virtual.rules:2:1")!=std::string::npos);
  options.resolver=[](auto,auto){return Result<syntax::ResolvedSource>::ok({"virtual.rules","include \"rules\";"});};fails(limeburg::load_rules("include \"rules\";","root.rules",options),Error::Code::Conflict);
  options={};options.depth=1;fails(limeburg::load_rules_file(fixtures+"/selection-includes.limeburg",options),Error::Code::ResourceLimit);
  options.resolver=[](auto,auto){return Result<syntax::ResolvedSource>::ok({"virtual.tree","tree t {node %1=A();root %1:reg;}"});};fails(limeburg::load_rules("ruleset x {include \"tree\";}","root.rules",options),Error::Code::Conflict);
  options={};options.bytes=8;fails(limeburg::load_rules_file(fixtures+"/selection-includes.limeburg",options),Error::Code::ResourceLimit);
  const char* repeated=R"(ruleset x {nonterminal reg;terminal INPUT(0);terminal PAIR(2);rule reg: INPUT() -> "" cost 0 external_only true;rule reg: PAIR(reg binding x register_class G,reg binding x register_class G) -> P side_effects true;}tree t {node %1=INPUT() register_class G required false;node %2=PAIR(%1,%1) side_effect true;root %2:reg;})";
  auto constrained=take(limeburg::load_rules(repeated));auto constraint_text=take(limeburg::print_rules(constrained));auto constraint_copy=take(limeburg::load_rules(constraint_text));CHECK(take(limeburg::print_rules(constraint_copy))==constraint_text);auto& constraint_tree=constraint_copy.trees[0];auto constraint_selection=take(limeburg::select(constraint_tree.nodes,constraint_tree.root,constraint_copy.rules,"reg"));CHECK(take(limeburg::emit_scheduler(constraint_tree.nodes,constraint_copy.rules,constraint_selection)).instructions[0].uses==std::vector<uint32_t>({1,1}));constraint_tree.nodes[0].register_class="F";fails(limeburg::select(constraint_tree.nodes,constraint_tree.root,constraint_copy.rules,"reg"),Error::Code::Unsatisfiable);
  fails(limeburg::load_rules("nonterminal reg;terminal C(0);tree t {node %1=C();node %2=C();root %1:reg;}"),Error::Code::Conflict);
  auto schedule_document=take(schedrow::load_schedrow(read(fixtures+"/scheduling.schedrow")));auto& text=schedule_document.regions[0];auto schedule=take(schedrow::schedule(text.region,schedule_document.machine));take(schedrow::verify(text.region,schedule_document.machine,schedule));CHECK(schedule[0].id==9&&schedule[1].id==2&&schedule[1].cycle==2&&schedule[2].id==5&&schedule[2].cycle==3);CHECK(text.region.instructions[0].throughput==0.5&&text.region.instructions[1].access->alias_sets==std::vector<uint32_t>{17});
  auto schedule_text=take(schedrow::print_schedrow(schedule_document));auto schedule_copy=take(schedrow::load_schedrow(schedule_text));CHECK(take(schedrow::print_schedrow(schedule_copy))==schedule_text);CHECK(schedule_copy.machine_metadata.at("custom").text()==schedule_document.machine_metadata.at("custom").text());take(schedrow::verify(schedule_copy.regions[0].region,schedule_copy.machine,schedule));
  fails(schedrow::load_schedrow("region x {instruction %1 {opcode=unknown;}}"),Error::Code::Unsupported);
  fails(schedrow::load_schedrow("region x {instruction %1 {opcode=A;latency=0;}dependency {producer=%1;consumer=%missing;kind=true;}}"),Error::Code::NotFound);
  fails(schedrow::load_schedrow("region x {instruction %1 {opcode=A;latency=0;group={kind=adjacent;};}}"),Error::Code::InvalidArgument);
  fails(schedrow::load_schedrow("region x {instruction %1 {opcode=A;latency=0;early_defs=[7];}}"),Error::Code::Conflict);
  fails(schedrow::load_schedrow("region x {instruction %1 {opcode=A;latency=0;resources=[{resource=ALU;duration=0;}];}}"),Error::Code::InvalidArgument);
  auto named=take(schedrow::load_schedrow("region x {instruction %name {opcode=A;latency=0;def %value;result_latency={value=3;};}}"));CHECK(named.regions[0].region.instructions[0].result_latency.at(0)==3);
  auto physical_latency=take(schedrow::load_schedrow("region x {instruction %1 {opcode=A;latency=4;def %1;implicit_def %1;result_latency={\"1\"=0;};implicit_result_latency={\"1\"=2;};}instruction %2 {opcode=B;latency=0;use %1;implicit_use %1;}}"));auto physical_text=take(schedrow::print_schedrow(physical_latency));auto physical_copy=take(schedrow::load_schedrow(physical_text));CHECK(take(schedrow::schedule(physical_copy.regions[0].region,{}))[1].cycle==2&&take(schedrow::print_schedrow(physical_copy))==physical_text);
  auto grouped=take(schedrow::load_schedrow(read(fixtures+"/grouping.schedrow")));CHECK(grouped.regions.size()==2&&grouped.regions[0].region.groups[0].kind==schedrow::GroupKind::Bundle);auto group_text=take(schedrow::print_schedrow(grouped));auto group_copy=take(schedrow::load_schedrow(group_text));CHECK(take(schedrow::print_schedrow(group_copy))==group_text);for(auto& r:group_copy.regions)take(schedrow::verify(r.region,group_copy.machine,take(schedrow::schedule(r.region,group_copy.machine))));auto bundle_issues=take(schedrow::schedule(group_copy.regions[0].region,group_copy.machine));CHECK(bundle_issues[0].slot==1&&bundle_issues[0].resources[0]=="B");
  auto annotated=take(schedrow::load_schedrow("region x {instruction %9 {opcode=A;latency=0;group={id=5;kind=pair;};}instruction %1 {opcode=B;latency=0;group={id=5;kind=pair;};}}"));CHECK(annotated.regions[0].region.groups[0].members==std::vector<uint32_t>({9,1}));auto annotation_text=take(schedrow::print_schedrow(annotated));CHECK(take(schedrow::print_schedrow(take(schedrow::load_schedrow(annotation_text))))==annotation_text);
  auto standalone_bundle=take(schedrow::load_schedrow("bundle named {instruction %1 {opcode=A;latency=0;}}"));CHECK(standalone_bundle.regions[0].region.groups[0].name=="named");
  fails(schedrow::load_schedrow("region x {bundle a {bundle b {instruction %1 {opcode=A;latency=0;}}}}"),Error::Code::Unsupported);
  fails(schedrow::load_schedrow("region x {instruction %9 {opcode=A;latency=0;group={id=5;kind=pair;};}instruction %1 {opcode=B;latency=0;group={id=5;kind=atomic;};}}"),Error::Code::Conflict);
  fails(schedrow::load_schedrow("region x {instruction %1 {opcode=A;latency=0;issue={width=2;};}}"),Error::Code::Unsupported);
  auto units=take(regtl::load_regtl(read(fixtures+"/allocation.regtl")));CHECK(units.size()==1&&units[0].functions.size()==1&&units[0].slots[0].alignment==8);auto& function=units[0].functions[0].function;auto live=take(regtl::analyze(function));CHECK(function.blocks[0].instructions[3].parallel&&function.blocks[0].instructions[3].transfers.size()==2);CHECK(live.live_in.at(function.blocks[1].id)==std::vector<uint32_t>{7});for(auto allocator:{regtl::linear_scan,regtl::greedy,regtl::graph_color}){auto assigned=take(allocator(live.problem));CHECK(assigned.regs.at(8)==2);take(regtl::verify(live.problem,assigned));}
  auto allocation_text=take(regtl::print_regtl(units));auto allocation_copy=take(regtl::load_regtl(allocation_text));CHECK(take(regtl::print_regtl(allocation_copy))==allocation_text);auto copy_live=take(regtl::analyze(allocation_copy[0].functions[0].function));CHECK(take(regtl::graph_color(copy_live.problem)).regs.at(8)==2);CHECK(allocation_copy[0].metadata.at("notes").text()==units[0].metadata.at("notes").text());
  fails(regtl::load_regtl("regtl x {regclass G=[$0];live %1:G [0,1] {} function f {block b {instruction I {use %missing;}}}}"),Error::Code::NotFound);
  fails(regtl::load_regtl("regtl x {regclass G=[$0];live %1:G [0,1] {} function f {block b {parallel {move $0 <- #1;move $0 <- #2;}}}}"),Error::Code::Conflict);
  fails(regtl::load_regtl("regtl x {regclass G=[$0];live %1:G [0,1] {fixed=$2;}}"),Error::Code::NotFound);
  fails(regtl::load_regtl("regtl x {regclass G=[$0];live %1:G [0,1] {allowed=[];}}"),Error::Code::Unsatisfiable);
  fails(regtl::load_regtl("regtl x {regclass G=[$0,$1];alias $0=$1;function f {block b {parallel {move $0 <- #1;move $1 <- #2;}}}}"),Error::Code::Conflict);
  auto quoted_constraints=take(regtl::load_regtl("regtl x {regclass G=[$0,$1];live %1:G [0,1] {\"fixed\"=\"$1\";}}"));CHECK(take(regtl::linear_scan(quoted_constraints[0].problem)).regs.at(1)==1);
});}
