file(MAKE_DIRECTORY "${BINARY}/tunah-cli")
set(input "${BINARY}/tunah-cli/input.term")
file(WRITE "${input}" "(iadd (iadd 12 30) (imul x 0))\n")
execute_process(COMMAND "${CLI}" --optimize-term
  --rules "${TUNERS}/vocabulary.tuner" --rules "${TUNERS}/alg-sim.tuner"
  --rules "${TUNERS}/const-folding.tuner" --trace "${input}"
  RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE diagnostics)
if(NOT status EQUAL 0 OR NOT output STREQUAL "42\n" OR NOT diagnostics MATCHES "cost=1" OR NOT diagnostics MATCHES "saturated=1")
  message(FATAL_ERROR "Tunah CLI optimization failed: ${status}; ${output}; ${diagnostics}")
endif()
file(WRITE "${input}" "(imul x 4)\n")
set(destination "${BINARY}/tunah-cli/output.term")
execute_process(COMMAND "${CLI}" --optimize-term --rules "${TUNERS}/vocabulary.tuner"
  --rules "${TUNERS}/strength-reduct.tuner" --op-cost imul 20 --op-cost ishl 1
  -o "${destination}" INPUT_FILE "${input}" RESULT_VARIABLE status ERROR_VARIABLE diagnostics)
file(READ "${destination}" output)
if(NOT status EQUAL 0 OR NOT output STREQUAL "(ishl x 2)\n" OR NOT diagnostics STREQUAL "")
  message(FATAL_ERROR "Tunah CLI cost/stdin/output failed: ${status}; ${output}; ${diagnostics}")
endif()
execute_process(COMMAND "${CLI}" --optimize-term --rules "${TUNERS}/vocabulary.tuner"
  --rules "${TUNERS}/strength-reduct.tuner" --iterations 0 --trace "${input}"
  RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE diagnostics)
if(NOT status EQUAL 0 OR NOT output STREQUAL "(imul x 4)\n" OR NOT diagnostics MATCHES "limit_reached=1")
  message(FATAL_ERROR "Tunah CLI bounded fallback failed: ${status}; ${output}; ${diagnostics}")
endif()
foreach(kind IN ITEMS guard missing wrong-mode bad-number unknown-cost malformed)
  if(kind STREQUAL "guard")
    set(arguments --optimize-term --rules "${TUNERS}/vocabulary.tuner" --rules "${TUNERS}/instr-climbing.tuner")
    set(expected "requires a host adapter")
  elseif(kind STREQUAL "missing")
    set(arguments --optimize-term --rules "${BINARY}/tunah-cli/missing.tuner")
    set(expected "cannot open rule file")
  elseif(kind STREQUAL "wrong-mode")
    set(arguments --rules "${TUNERS}/vocabulary.tuner")
    set(expected "require --optimize-term")
  elseif(kind STREQUAL "bad-number")
    set(arguments --optimize-term --iterations -1)
    set(expected "non-negative integer")
  elseif(kind STREQUAL "unknown-cost")
    set(arguments --optimize-term --rules "${TUNERS}/vocabulary.tuner" --op-cost missing 1)
    set(expected "cost for undeclared operator")
  else()
    file(WRITE "${input}" "(iadd 1 2\n")
    set(arguments --optimize-term --rules "${TUNERS}/vocabulary.tuner")
    set(expected "input.term:2:1:.*unterminated")
  endif()
  execute_process(COMMAND "${CLI}" ${arguments} "${input}"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE diagnostics)
  if(NOT status EQUAL 1 OR NOT diagnostics MATCHES "${expected}" OR NOT output STREQUAL "")
    message(FATAL_ERROR "Tunah CLI ${kind} diagnostic failed: ${status}; ${output}; ${diagnostics}")
  endif()
endforeach()
