execute_process(COMMAND "${LUA}" "${SOURCE}/tests/vmweave.lua" "${SOURCE}" "${BINARY}/vmweave-test.c" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "VMWeave DSL regression failed")
endif()
execute_process(COMMAND "${CC}" -std=c99 -Wall -Wextra -Werror "${BINARY}/vmweave-test.c" -o "${BINARY}/vmweave-test" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Generated VM did not compile")
endif()
execute_process(COMMAND "${BINARY}/vmweave-test" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Generated VM produced the wrong state")
endif()
