#include "internal.hpp"
#include <set>

namespace limestone::vmweave {
namespace {
bool selected(const Specification& s,std::string_view c) {return std::find(s.components.begin(),s.components.end(),c)!=s.components.end();}
std::pair<size_t,size_t> counts(const std::string& effect) {
  std::istringstream in(effect); std::string token; size_t before=0,after=0; bool output=false;
  while(in>>token) {if(token=="--") output=true; else if(token!="(" && token!=")") (output?after:before)++;}
  return {before,after};
}
std::string replace(std::string text,const std::string& name) {
  size_t at=0; while((at=text.find("@",at))!=std::string::npos) {text.replace(at,1,name); at+=name.size();} return text;
}
std::string runtime_checks(const std::string& n) {
  return replace(R"C(
static inline int @_vw_check(@_vm *vm, uint32_t opcode, size_t *base, const @_metadata **metadata) {
  const @_metadata *info = @_lookup(opcode);
  if(!vm || !info) return -1;
  if(vm->vw_error) return vm->vw_error;
  if(info->operands && (!vm->vw_current || vm->vw_current->operand_count != info->operands)) return -4;
  if(vm->vw_sp < info->inputs) { @_vw_fail(vm,-2); return -2; }
  *base = vm->vw_sp - info->inputs;
  if(*base > sizeof(vm->vw_stack)/sizeof(vm->vw_stack[0]) || info->outputs > sizeof(vm->vw_stack)/sizeof(vm->vw_stack[0]) - *base) { @_vw_fail(vm,-3); return -3; }
  *metadata = info; return 0;
}
static inline int @_vw_finish(@_vm *vm, size_t base, const @_metadata *info) {
  if(!vm->vw_error && vm->vw_sp != base + info->outputs) @_vw_fail(vm,-6);
  return vm->vw_error;
}
)C",n);
}
std::string header(const Module& m) {
  const auto& s=m.configuration; const auto& n=s.name;
  std::ostringstream o;
  o<<"/* Generated by VMWeave from STK-00 v1. Do not edit. */\n#ifndef "<<n<<"_VMWEAVE_H\n#define "<<n<<"_VMWEAVE_H\n#include <stdint.h>\n#include <stddef.h>\n#include <stdlib.h>\n#include <string.h>\n#include <limits.h>\n#ifdef __cplusplus\nextern \"C\" {\n#endif\n";
  o<<"typedef "<<s.cell<<" "<<n<<"_cell;\ntypedef struct "<<n<<"_vm "<<n<<"_vm;\ntypedef void (*"<<n<<"_handler)("<<n<<"_vm *);\n";
  o<<replace(R"C(
typedef struct { uint32_t opcode; size_t operand_count; @_cell operands[16]; } @_instruction;
typedef struct { @_instruction *data; size_t size, capacity; } @_tape;
typedef struct { const char *name; uint32_t opcode; size_t operands, inputs, outputs; const char *flow; } @_metadata;
)C",n);
  if(s.execution=="direct") o<<replace(R"C(
typedef struct { @_handler address; @_instruction instruction; } @_threaded;
)C",n);
  if(selected(s,"memory")) o<<replace(R"C(
typedef struct {
  void *context;
  void *(*allocate)(void *, size_t);
  void *(*reallocate)(void *, void *, size_t);
  void (*release)(void *, void *);
} @_allocator;
)C",n);
  if(selected(s,"frame")) o<<replace(R"C(
typedef struct { size_t return_address, stack_base; @_cell locals[16]; } @_activation;
)C",n);
  if(selected(s,"object")) o<<replace(R"C(
typedef struct @_object { struct @_object *next; uint32_t kind; size_t size; unsigned char data[]; } @_object;
)C",n);
  if(selected(s,"module")) o<<replace(R"C(
typedef struct { const char *name; void *address; } @_symbol;
typedef struct { const char *name; const @_symbol *exports; size_t export_count; const @_tape *code; } @_module;
)C",n);
  if(selected(s,"atomic")) o<<replace(R"C(
enum { @_nil=0, @_integer=1, @_floating=2, @_boolean=3, @_reference=4 };
typedef struct { uint32_t tag; union { @_cell integer; double floating; int boolean; void *reference; } value; } @_atomic;
)C",n);
  if(selected(s,"optim")) o<<replace(R"C(
typedef struct { uintptr_t key; void *value; uint64_t epoch; } @_cache_entry;
)C",n);
  if(selected(s,"jit")) o<<replace(R"C(
typedef struct {
  void *context;
  int (*compile)(void *, const char *, const @_tape *, void **);
  int (*execute)(void *, void *, @_vm *);
  void (*release)(void *, void *);
} @_jit_backend;
)C",n);
  o<<"struct "<<n<<"_vm {\n";
  static const std::map<std::string,std::string> types={{"u8","uint8_t"},{"u16","uint16_t"},{"u32","uint32_t"},{"u64","uint64_t"},{"i8","int8_t"},{"i16","int16_t"},{"i32","int32_t"},{"i64","int64_t"},{"f32","float"},{"f64","double"},{"ptr","void *"},{"size","size_t"}};
  for(const auto& f:s.fields) {o<<"  "<<types.at(f.type)<<' '<<f.name; if(f.count) o<<'['<<f.count<<']'; o<<";\n";}
  o<<"  "<<n<<"_cell vw_stack["<<s.stack_capacity<<"];\n  size_t vw_sp, vw_pc, vw_code_size;\n  int vw_error, vw_halted;\n  const "<<n<<"_instruction *vw_current;\n";
  if(s.hooks) o<<"  void *vmweave_userdata;\n  int (*vmweave_before)("<<n<<"_vm *, uint32_t, void *);\n  void (*vmweave_after)("<<n<<"_vm *, uint32_t, void *);\n";
  if(selected(s,"memory")) o<<"  "<<n<<"_allocator vw_allocator;\n";
  if(selected(s,"object")) o<<"  "<<n<<"_object *vw_objects;\n";
  if(selected(s,"module")) o<<"  const "<<n<<"_module *vw_module;\n";
  if(selected(s,"frame")) o<<"  "<<n<<"_activation vw_frames["<<s.frame_capacity<<"];\n  size_t vw_frame_count;\n";
  if(selected(s,"ipc")) o<<"  "<<n<<"_cell vw_messages["<<s.ipc_capacity<<"];\n  size_t vw_message_head, vw_message_count;\n";
  if(selected(s,"optim")) o<<"  "<<n<<"_cache_entry vw_cache[16];\n  uint64_t vw_epoch;\n";
  o<<"};\n";
  std::vector<std::string> members={"vw_stack","vw_sp","vw_pc","vw_code_size","vw_error","vw_halted","vw_current"};
  std::string abi_signature=n+":"+s.cell;
  for(const auto& f:s.fields) {members.push_back(f.name); abi_signature+=":"+f.name+":"+f.type+":"+std::to_string(f.count);}
  if(s.hooks) {members.insert(members.end(),{"vmweave_userdata","vmweave_before","vmweave_after"}); abi_signature+=":hooks";}
  for(const auto& [component,fields]:std::map<std::string,std::vector<std::string>>{
    {"memory",{"vw_allocator"}},{"object",{"vw_objects"}},{"module",{"vw_module"}},
    {"frame",{"vw_frames","vw_frame_count"}},{"ipc",{"vw_messages","vw_message_head","vw_message_count"}},
    {"optim",{"vw_cache","vw_epoch"}}}) if(selected(s,component)) {members.insert(members.end(),fields.begin(),fields.end()); abi_signature+=":"+component;}
  uint64_t seed=UINT64_C(14695981039346656037);
  for(unsigned char c:abi_signature) seed=(seed^c)*UINT64_C(1099511628211);
  o<<"static inline uint64_t "<<n<<"_vw_abi(void) {\n  struct alignment_probe { char byte; "<<n<<"_vm state; };\n  uint64_t h=UINT64_C("<<seed<<");\n";
  auto mix=[&](const std::string& expression){o<<"  h=(h^(uint64_t)("<<expression<<"))*UINT64_C(1099511628211);\n";};
  mix("sizeof("+n+"_vm)"); mix("offsetof(struct alignment_probe,state)"); mix("sizeof("+n+"_cell)");
  for(const auto& field:members) {mix("offsetof("+n+"_vm,"+field+")"); mix("sizeof((("+n+"_vm *)0)->"+field+")");}
  mix("sizeof("+n+"_instruction)"); mix("offsetof("+n+"_instruction,operands)"); mix("offsetof("+n+"_instruction,operand_count)");
  o<<"  return h;\n}\n";
  for(const auto& w:m.words) o<<"void "<<n<<'_'<<w.name<<'('<<n<<"_vm *vm);\n#define "<<n<<"_opcode_"<<w.name<<' '<<w.opcode<<"u\n";
  o<<replace(R"C(
static inline void @_init(@_vm *vm) { if(vm) memset(vm, 0, sizeof(*vm)); }
static inline void @_vw_fail(@_vm *vm, int status) { if(vm && !vm->vw_error) vm->vw_error = status ? status : -1; }
static inline @_cell @_vw_pop(@_vm *vm) {
  if(!vm || vm->vw_error) return 0;
  if(!vm->vw_sp) { @_vw_fail(vm, -2); return 0; }
  if(vm->vw_sp > sizeof(vm->vw_stack)/sizeof(vm->vw_stack[0])) { @_vw_fail(vm, -3); return 0; }
  return vm->vw_stack[--vm->vw_sp];
}
static inline void @_vw_push(@_vm *vm, @_cell value) {
  if(!vm || vm->vw_error) return;
  if(vm->vw_sp >= sizeof(vm->vw_stack)/sizeof(vm->vw_stack[0])) { @_vw_fail(vm, -3); return; }
  vm->vw_stack[vm->vw_sp++] = value;
}
static inline @_cell @_vw_operand(@_vm *vm, size_t index) {
  if(!vm || !vm->vw_current || index >= vm->vw_current->operand_count) { @_vw_fail(vm, -4); return 0; }
  return vm->vw_current->operands[index];
}
static inline void @_vw_jump(@_vm *vm, @_cell target) {
  if(!vm || vm->vw_error) return;
  if((uintmax_t)target >= vm->vw_code_size) { @_vw_fail(vm, -4); return; }
  vm->vw_pc = (size_t)target;
}
static inline void @_vw_halt(@_vm *vm) { if(vm) vm->vw_halted=1; }
)C",n);
  o<<"static inline const "<<n<<"_metadata *"<<n<<"_lookup(uint32_t opcode) {\n  static const "<<n<<"_metadata table[] = {\n";
  for(const auto& w:m.words) {auto [a,b]=counts(w.effect); o<<"    {"<<c_string(w.name)<<", "<<w.opcode<<"u, "<<w.operands.size()<<", "<<a<<", "<<b<<", "<<c_string(w.flow)<<"},\n";}
  o<<"    {NULL,0,0,0,0,NULL}\n  };\n  size_t i; for(i=0; table[i].name; ++i) if(table[i].opcode==opcode) return &table[i];\n  return NULL;\n}\n";
  o<<"static inline int "<<n<<"_vw_label_operand(uint32_t opcode, size_t index) {\n  (void)index; switch(opcode) {\n";
  for(const auto& w:m.words) {
    o<<"  case "<<w.opcode<<"u: return 0";
    for(size_t j=0;j<w.operands.size();++j) if(w.operands[j]=="label") o<<" || index=="<<j;
    o<<";\n";
  }
  o<<"  default: return 0;\n  }\n}\n";
  o<<replace(R"C(
static inline int @_vw_validate_instruction(const @_instruction *instruction, size_t size) {
  size_t j; const @_metadata *info;
  if(!instruction) return -1;
  info=@_lookup(instruction->opcode);
  if(!info || info->operands!=instruction->operand_count) return -4;
  for(j=0;j<info->operands;++j)
    if(@_vw_label_operand(info->opcode,j) && (uintmax_t)instruction->operands[j]>=size) return -4;
  return 0;
}
)C",n);
  o<<runtime_checks(n);
  // Only selected component APIs appear in the generated public header.
  if(selected(s,"dispatch")) {
    o<<replace("int @_step(@_vm *, uint32_t);\n",n);
    if(s.execution=="direct") o<<replace("int @_run_direct(@_vm *, const @_threaded *, size_t, size_t);\nint @_thread(const @_tape *, @_threaded *, size_t);\n",n);
    else o<<replace("int @_run(@_vm *, const @_tape *, size_t);\n",n);
  }
  const std::map<std::string,std::string> prototypes={
    {"token","const char *@_token(uint32_t);\n"},
    {"compile","int @_compile(const char *, @_tape *);\n"},
    {"tape","int @_tape_validate(const @_tape *);\n"},
    {"rewrite","int @_rewrite(@_tape *);\n"},
    {"memory","int @_memory_set(@_vm *, @_allocator);\nvoid *@_alloc(@_vm *, size_t);\nvoid *@_memory_resize(@_vm *, void *, size_t);\nvoid @_free(@_vm *, void *);\n"},
    {"frame","int @_call(@_vm *, @_cell);\nint @_ret(@_vm *);\n"},
    {"object","@_object *@_object_new(@_vm *, uint32_t, size_t);\nint @_object_read(const @_object *, size_t, void *, size_t);\nint @_object_write(@_object *, size_t, const void *, size_t);\nint @_object_delete(@_vm *, @_object *);\nint @_object_clear(@_vm *);\n"},
    {"ipc","int @_ipc_send(@_vm *, @_cell);\nint @_ipc_receive(@_vm *, @_cell *);\n"},
    {"module","void *@_module_find(const @_module *, const char *);\nint @_module_validate(const @_module *);\nint @_module_load(@_vm *, const @_module *);\n"},
    {"optim","void @_optim_invalidate(@_vm *);\nvoid @_optim_store(@_vm *, uintptr_t, void *);\nvoid *@_optim_lookup(@_vm *, uintptr_t);\n"},
    {"atomic","@_atomic @_atomic_integer(@_cell);\n@_atomic @_atomic_float(double);\n@_atomic @_atomic_bool(int);\n@_atomic @_atomic_reference(void *);\n@_atomic @_atomic_nil(void);\n"},
    {"jit","int @_jit_compile(const @_jit_backend *, const @_tape *, void **);\nint @_jit_execute(const @_jit_backend *, void *, @_vm *);\nvoid @_jit_release(const @_jit_backend *, void *);\n"},
    {"srtbl","@_handler @_vw_routine(uint32_t);\n"},
    {"addrtbl","const @_handler *@_vw_address(uint32_t);\n"},
    {"insntbl","@_handler @_vw_instruction(uint32_t);\n"}
  };
  for(const auto& [c,decl]:prototypes) if(selected(s,c)) o<<replace(decl,n);
  if(selected(s,"memory") && s.allocator=="system") o<<replace("int @_memory_system(@_vm *);\n",n);
  o<<"#ifdef __cplusplus\n}\n#endif\n#endif\n"; return o.str();
}
std::string handlers(const Module& m) {
  auto n=m.configuration.name; std::ostringstream o;
  o<<"#define vm_pop() "<<n<<"_vw_pop(vm)\n#define vm_push(x) "<<n<<"_vw_push(vm,(x))\n#define vm_operand(i) "<<n<<"_vw_operand(vm,(i))\n#define vm_jump(x) "<<n<<"_vw_jump(vm,(x))\n#define vm_halt() "<<n<<"_vw_halt(vm)\n#define vm_fail(x) "<<n<<"_vw_fail(vm,(x))\n";
  if(selected(m.configuration,"frame")) o<<"#define vm_call(x) "<<n<<"_call(vm,(x))\n#define vm_return() "<<n<<"_ret(vm)\n";
  if(selected(m.configuration,"memory")) o<<"#define vm_alloc(x) "<<n<<"_alloc(vm,(x))\n#define vm_free(x) "<<n<<"_free(vm,(x))\n";
  for(const auto& w:m.words) {
    o<<"void "<<n<<'_'<<w.name<<'('<<n<<"_vm *vm) {\n  typedef "<<n<<"_cell cell; (void)sizeof(cell);\n  (void)vm;\n";
    for(size_t i=0;i<w.operands.size();++i) o<<"  cell operand"<<i<<" = vm_operand("<<i<<"); (void)operand"<<i<<";\n";
    if(!w.source.file.empty() && w.source.line) o<<"#line "<<w.source.line<<' '<<c_string(w.source.file)<<'\n';
    o<<w.c_body<<"\n#line 1 \"<VMWeave generated>\"\n}\n";
  }
  for(const auto& macro:{"vm_pop","vm_push","vm_operand","vm_jump","vm_halt","vm_fail","vm_call","vm_return","vm_alloc","vm_free"}) o<<"#undef "<<macro<<'\n';
  return o.str();
}
std::string table(const Module& m,const std::string& component) {
  auto n=m.configuration.name; std::ostringstream o;
  bool indirect=component=="addrtbl";
  std::string method=component=="srtbl"?"routine":indirect?"address":"instruction";
  o<<(indirect?"const ":"")<<n<<"_handler "<<(indirect?"*":"")<<n<<"_vw_"<<method<<"(uint32_t opcode) {\n";
  if(indirect) for(const auto& w:m.words) o<<"  static const "<<n<<"_handler slot_"<<w.name<<" = "<<n<<'_'<<w.name<<";\n";
  o<<"  switch(opcode) {\n";
  for(const auto& w:m.words) o<<"  case "<<w.opcode<<"u: return "<<(indirect?"&slot_":n+"_")<<w.name<<";\n";
  o<<"  default: return NULL;\n  }\n}\n"; return o.str();
}
std::string dispatch(const Module& m) {
  auto n=m.configuration.name; const auto& s=m.configuration; std::ostringstream o;
  o<<replace(R"C(
int @_step(@_vm *vm, uint32_t opcode) {
  size_t base=0; const @_metadata *info=NULL;
  int status=@_vw_check(vm,opcode,&base,&info); if(status) return status;
)C",n);
  if(s.hooks) o<<"  if(vm->vmweave_before) { status=vm->vmweave_before(vm,opcode,vm->vmweave_userdata); if(status) return status; }\n";
  if(s.execution=="switch" || s.execution=="direct") {
    o<<"  switch(opcode) {\n"; for(const auto& w:m.words) o<<"  case "<<w.opcode<<"u: "<<n<<'_'<<w.name<<"(vm); break;\n"; o<<"  default: return -1;\n  }\n";
  } else if(s.execution=="subroutine") o<<"  "<<n<<"_handler fn="<<n<<"_vw_routine(opcode); if(!fn) return -1; fn(vm);\n";
  else o<<"  const "<<n<<"_handler *slot="<<n<<"_vw_address(opcode); if(!slot || !*slot) return -1; (*slot)(vm);\n";
  if(s.hooks) o<<"  if(vm->vmweave_after) vm->vmweave_after(vm,opcode,vm->vmweave_userdata);\n";
  o<<"  return "<<n<<"_vw_finish(vm,base,info);\n}\n";
  // Direct tapes contain callable addresses, not tokens. The opcode retained
  // alongside them supplies validation and observation metadata only.
  if(s.execution=="direct") {
    o<<replace(R"C(
int @_thread(const @_tape *tape, @_threaded *out, size_t capacity) {
  size_t i;
  if(!tape || tape->size > tape->capacity || tape->size > capacity || (tape->size && (!out || !tape->data))) return -1;
  for(i=0;i<tape->size;++i) if(@_vw_validate_instruction(&tape->data[i],tape->size)) return -4;
  for(i=0;i<tape->size;++i) { out[i].address=@_vw_instruction(tape->data[i].opcode); out[i].instruction=tape->data[i]; }
  return 0;
}
int @_run_direct(@_vm *vm, const @_threaded *code, size_t size, size_t budget) {
  size_t steps=0, i; int status=0;
  if(!vm || (size && !code)) return -1;
  if(vm->vw_pc>size) return -4;
  for(i=0;i<size;++i) if(@_vw_validate_instruction(&code[i].instruction,size) || !code[i].address || code[i].address!=@_vw_instruction(code[i].instruction.opcode)) return -4;
  vm->vw_code_size=size; vm->vw_halted=0;
  while(!vm->vw_halted && vm->vw_pc<size) {
    const @_threaded *entry; const @_metadata *info=NULL; size_t base=0, origin=vm->vw_pc;
    if(steps++>=budget) { status=-7; break; }
    entry=&code[vm->vw_pc];
    if(!entry->address || entry->address!=@_vw_instruction(entry->instruction.opcode)) {status=-4; break;}
    vm->vw_current=&entry->instruction;
    status=@_vw_check(vm,entry->instruction.opcode,&base,&info); if(status) break;
)C",n);
    if(s.hooks) o<<"    if(vm->vmweave_before) {status=vm->vmweave_before(vm,entry->instruction.opcode,vm->vmweave_userdata); if(status) break;}\n";
    o<<"    ++vm->vw_pc; entry->address(vm);\n";
    if(s.hooks) o<<"    if(vm->vmweave_after) vm->vmweave_after(vm,entry->instruction.opcode,vm->vmweave_userdata);\n";
    o<<"    status="<<n<<"_vw_finish(vm,base,info); if(status) {vm->vw_pc=origin; break;}\n  }\n  vm->vw_current=NULL; return status;\n}\n";
  } else {
    o<<replace(R"C(
int @_run(@_vm *vm, const @_tape *tape, size_t budget) {
  size_t steps=0, i; int status=0;
  if(!vm || !tape || tape->size>tape->capacity || (tape->size && !tape->data)) return -1;
  if(vm->vw_pc>tape->size) return -4;
  for(i=0;i<tape->size;++i) if(@_vw_validate_instruction(&tape->data[i],tape->size)) return -4;
  vm->vw_code_size=tape->size; vm->vw_halted=0;
  while(!vm->vw_halted && vm->vw_pc<tape->size) {
    const @_metadata *info; size_t origin=vm->vw_pc;
    if(steps++>=budget) {status=-7; break;}
    vm->vw_current=&tape->data[vm->vw_pc]; info=@_lookup(vm->vw_current->opcode);
    if(!info || vm->vw_current->operand_count!=info->operands) {status=-4; break;}
    ++vm->vw_pc; status=@_step(vm,vm->vw_current->opcode); if(status) {vm->vw_pc=origin; break;}
  }
  vm->vw_current=NULL; return status;
}
)C",n);
  }
  return o.str();
}
std::string compiler(const Module& m) {
  auto n=m.configuration.name;
  std::string text=R"C(
#include <errno.h>
#include <ctype.h>
typedef struct { char name[128]; size_t address; } @_vw_label;
static int @_vw_token(const char **source, char *out, size_t capacity) {
  const char *p=*source; size_t count=0;
  for(;;) {
    while(*p && isspace((unsigned char)*p)) ++p;
    if(*p!='#') break;
    while(*p && *p!='\n') ++p;
  }
  if(!*p) { *source=p; return 0; }
  while(*p && !isspace((unsigned char)*p) && *p!='#') {
    if(count+1>=capacity) return -1;
    out[count++]=*p++;
  }
  out[count]=0; *source=p; return 1;
}
static const @_metadata *@_vw_mnemonic(const char *name) {
)C";
  for(const auto& w:m.words) text+="  if(strcmp(name,"+c_string(w.name)+")==0) return @_lookup("+std::to_string(w.opcode)+"u);\n";
  text+=R"C(
  return NULL;
}
/* Caller-owned output, transactional validation, labels are instruction indices.
   No allocator is selected by the compiler. */
int @_compile(const char *source, @_tape *out) {
  @_vw_label labels[256]; size_t label_count=0, count=0, total=0, pass;
  char token[128];
  if(!source || !out || out->size>out->capacity || (out->capacity && !out->data)) return -1;
  /* Passes 0 and 1 validate labels/operands/capacity. Pass 2 writes only after
     validation has succeeded, so failures leave the tape unchanged. */
  for(pass=0;pass<3;++pass) {
    const char *cursor=source; int got; count=0;
    while((got=@_vw_token(&cursor,token,sizeof(token)))>0) {
      size_t len=strlen(token), j; const @_metadata *info;
      if(token[len-1]==':') {
        token[len-1]=0; if(!token[0]) return -4;
        if(pass==0) {
          if(label_count==256) return -3;
          for(j=0;j<label_count;++j) if(strcmp(labels[j].name,token)==0) return -4;
          strcpy(labels[label_count].name,token); labels[label_count++].address=count;
        }
        continue;
      }
      info=@_vw_mnemonic(token); if(!info) return -4;
      if(count>=out->capacity) return -3;
      if(pass==2) {memset(&out->data[count],0,sizeof(out->data[count])); out->data[count].opcode=info->opcode; out->data[count].operand_count=info->operands;}
      for(j=0;j<info->operands;++j) {
        @_cell value=0; char *end; intmax_t parsed;
        if(@_vw_token(&cursor,token,sizeof(token))!=1) return -4;
        if(token[0]=='&') {
          size_t k;
          if(pass) {for(k=0;k<label_count && strcmp(labels[k].name,token+1)!=0;++k) {} if(k==label_count) return -4; value=(@_cell)labels[k].address;}
        } else {
          errno=0; parsed=strtoimax(token,&end,0);
          if(errno || *end || end==token || (intmax_t)(@_cell)parsed!=parsed) return -4;
          value=(@_cell)parsed;
        }
        if(pass && @_vw_label_operand(info->opcode,j) && (uintmax_t)value>=total) return -4;
        if(pass==2) out->data[count].operands[j]=value;
      }
      ++count;
    }
    if(got<0) return -4;
    if(pass==0) total=count;
  }
  out->size=count; return 0;
}
)C";
  if(m.configuration.cell=="uint64_t") {
    auto at=text.find("intmax_t parsed;"); text.replace(at,std::string("intmax_t parsed;").size(),"uintmax_t parsed;");
    at=text.find("parsed=strtoimax(token,&end,0)"); text.replace(at,std::string("parsed=strtoimax(token,&end,0)").size(),"parsed=strtoumax(token,&end,0)");
    at=text.find("if(errno || *end || end==token || (intmax_t)(@_cell)parsed!=parsed)");
    text.replace(at,std::string("if(errno || *end || end==token || (intmax_t)(@_cell)parsed!=parsed)").size(),"if(token[0]=='-' || errno || *end || end==token || (uintmax_t)(@_cell)parsed!=parsed)");
  }
  return "#include <inttypes.h>\n"+replace(text,n);
}
std::string optional(const Module& m,const std::string& component) {
  const auto& s=m.configuration; auto n=s.name; std::string text;
  if(component=="tape") text=R"C(
int @_tape_validate(const @_tape *tape) {
  size_t i;
  if(!tape || tape->size>tape->capacity || (tape->size && !tape->data)) return -1;
  for(i=0;i<tape->size;++i) {
    if(@_vw_validate_instruction(&tape->data[i],tape->size)) return -4;
  }
  return 0;
}
)C";
  else if(component=="memory") {
    text=R"C(
int @_memory_set(@_vm *vm, @_allocator allocator) {
  if(!vm || !allocator.allocate || !allocator.release) return -1;
)C";
    if(selected(s,"object")) text+="  if(vm->vw_objects) return -1;\n";
    text+=R"C(
  vm->vw_allocator=allocator; return 0;
}
void *@_alloc(@_vm *vm, size_t bytes) {
  void *value;
  if(!vm || vm->vw_error || !vm->vw_allocator.allocate) { @_vw_fail(vm,-8); return NULL; }
  value=vm->vw_allocator.allocate(vm->vw_allocator.context,bytes);
  if(!value && bytes) @_vw_fail(vm,-8);
  return value;
}
void *@_memory_resize(@_vm *vm, void *value, size_t bytes) {
  void *result;
  if(!vm || vm->vw_error || !vm->vw_allocator.reallocate) { @_vw_fail(vm,-8); return NULL; }
  result=vm->vw_allocator.reallocate(vm->vw_allocator.context,value,bytes);
  if(!result && bytes) @_vw_fail(vm,-8);
  return result;
}
void @_free(@_vm *vm, void *value) {
  if(vm && value && vm->vw_allocator.release) vm->vw_allocator.release(vm->vw_allocator.context,value);
}
)C";
    if(s.allocator=="system") text+=R"C(
static void *@_vw_system_allocate(void *context, size_t bytes) { (void)context; return malloc(bytes); }
static void *@_vw_system_resize(void *context, void *p, size_t bytes) { (void)context; return realloc(p,bytes); }
static void @_vw_system_free(void *context, void *p) { (void)context; free(p); }
int @_memory_system(@_vm *vm) {
  @_allocator a={NULL,@_vw_system_allocate,@_vw_system_resize,@_vw_system_free}; return @_memory_set(vm,a);
}
)C";
  } else if(component=="object") text=R"C(
@_object *@_object_new(@_vm *vm, uint32_t kind, size_t bytes) {
  @_object *object;
  if(bytes>SIZE_MAX-sizeof(*object)) { @_vw_fail(vm,-8); return NULL; }
  object=(@_object *)@_alloc(vm,sizeof(*object)+bytes); if(!object) return NULL;
  object->kind=kind; object->size=bytes; memset(object->data,0,bytes);
  object->next=vm->vw_objects; vm->vw_objects=object; return object;
}
int @_object_read(const @_object *object, size_t offset, void *out, size_t bytes) {
  if(!object || (bytes && !out) || offset>object->size || bytes>object->size-offset) return -4;
  if(bytes) memcpy(out,object->data+offset,bytes); return 0;
}
int @_object_write(@_object *object, size_t offset, const void *in, size_t bytes) {
  if(!object || (bytes && !in) || offset>object->size || bytes>object->size-offset) return -4;
  if(bytes) memcpy(object->data+offset,in,bytes); return 0;
}
int @_object_delete(@_vm *vm, @_object *object) {
  @_object **link;
  if(!vm || !object) return -1;
  for(link=&vm->vw_objects; *link && *link!=object; link=&(*link)->next) {}
  if(!*link) return -1;
  *link=object->next; @_free(vm,object); return 0;
}
int @_object_clear(@_vm *vm) {
  if(!vm) return -1;
  while(vm->vw_objects) { @_object *next=vm->vw_objects->next; @_free(vm,vm->vw_objects); vm->vw_objects=next; }
  return 0;
}
)C";
  else if(component=="frame") text=R"C(
int @_call(@_vm *vm, @_cell target) {
  @_activation *frame;
  if(!vm || vm->vw_error) return vm ? vm->vw_error : -1;
  if((uintmax_t)target>=vm->vw_code_size) { @_vw_fail(vm,-4); return -4; }
  if(vm->vw_frame_count>=sizeof(vm->vw_frames)/sizeof(vm->vw_frames[0])) { @_vw_fail(vm,-3); return -3; }
  frame=&vm->vw_frames[vm->vw_frame_count++]; memset(frame,0,sizeof(*frame));
  frame->return_address=vm->vw_pc; frame->stack_base=vm->vw_sp; vm->vw_pc=(size_t)target; return 0;
}
int @_ret(@_vm *vm) {
  if(!vm || vm->vw_error) return vm ? vm->vw_error : -1;
  if(!vm->vw_frame_count) { @_vw_fail(vm,-2); return -2; }
  vm->vw_pc=vm->vw_frames[--vm->vw_frame_count].return_address; return 0;
}
)C";
  else if(component=="ipc") text=R"C(
int @_ipc_send(@_vm *vm, @_cell value) {
  size_t capacity;
  if(!vm) return -1;
  capacity=sizeof(vm->vw_messages)/sizeof(vm->vw_messages[0]);
  if(vm->vw_message_count==capacity) return -3;
  vm->vw_messages[(vm->vw_message_head+vm->vw_message_count++)%capacity]=value; return 0;
}
int @_ipc_receive(@_vm *vm, @_cell *value) {
  if(!vm || !value) return -1;
  if(!vm->vw_message_count) return -2;
  *value=vm->vw_messages[vm->vw_message_head]; --vm->vw_message_count;
  vm->vw_message_head=(vm->vw_message_head+1)%(sizeof(vm->vw_messages)/sizeof(vm->vw_messages[0])); return 0;
}
)C";
  else if(component=="module") text=R"C(
void *@_module_find(const @_module *module, const char *name) {
  size_t i;
  if(!module || !name || (module->export_count && !module->exports)) return NULL;
  for(i=0;i<module->export_count;++i) if(module->exports[i].name && strcmp(module->exports[i].name,name)==0) return module->exports[i].address;
  return NULL;
}
int @_module_validate(const @_module *module) {
  size_t i,j;
  if(!module || !module->name || (module->export_count && !module->exports)) return -1;
  for(i=0;i<module->export_count;++i) {
    if(!module->exports[i].name) return -4;
    for(j=0;j<i;++j) if(strcmp(module->exports[i].name,module->exports[j].name)==0) return -4;
  }
  if(module->code) {
    const @_tape *tape=module->code;
    if(tape->size>tape->capacity || (tape->size && !tape->data)) return -4;
    for(i=0;i<tape->size;++i) if(@_vw_validate_instruction(&tape->data[i],tape->size)) return -4;
  }
  return 0;
}
int @_module_load(@_vm *vm, const @_module *module) {
  int status;
  if(!vm) return -1;
  status=@_module_validate(module); if(status) return status;
  vm->vw_module=module; vm->vw_pc=0; vm->vw_halted=0;
  vm->vw_code_size=module->code ? module->code->size : 0;
  return 0;
}
)C";
  else if(component=="atomic") text=R"C(
@_atomic @_atomic_integer(@_cell value) { @_atomic out; memset(&out,0,sizeof(out)); out.tag=@_integer; out.value.integer=value; return out; }
@_atomic @_atomic_float(double value) { @_atomic out; memset(&out,0,sizeof(out)); out.tag=@_floating; out.value.floating=value; return out; }
@_atomic @_atomic_bool(int value) { @_atomic out; memset(&out,0,sizeof(out)); out.tag=@_boolean; out.value.boolean=!!value; return out; }
@_atomic @_atomic_reference(void *value) { @_atomic out; memset(&out,0,sizeof(out)); out.tag=@_reference; out.value.reference=value; return out; }
@_atomic @_atomic_nil(void) { @_atomic out; memset(&out,0,sizeof(out)); return out; }
)C";
  else if(component=="optim") text=R"C(
void @_optim_invalidate(@_vm *vm) { if(vm) { memset(vm->vw_cache,0,sizeof(vm->vw_cache)); ++vm->vw_epoch; } }
void @_optim_store(@_vm *vm, uintptr_t key, void *value) {
  @_cache_entry *entry; if(!vm) return; entry=&vm->vw_cache[key%16]; entry->key=key; entry->value=value; entry->epoch=vm->vw_epoch;
}
void *@_optim_lookup(@_vm *vm, uintptr_t key) {
  @_cache_entry *entry; if(!vm) return NULL; entry=&vm->vw_cache[key%16];
  return entry->key==key && entry->epoch==vm->vw_epoch ? entry->value : NULL;
}
)C";
  else if(component=="jit") {
    auto stk=print_stk(m).value();
    text="static const char @_vw_jit_stk[]="+c_string(stk)+";\n";
    text+=R"C(
int @_jit_compile(const @_jit_backend *backend, const @_tape *code, void **handle) {
  int status;
  if(!handle) return -1; *handle=NULL;
  if(!backend || !backend->compile || !backend->execute || !backend->release) return -9;
  status=@_tape_validate(code); if(status) return status;
  status=backend->compile(backend->context,@_vw_jit_stk,code,handle);
  if(status && *handle) {backend->release(backend->context,*handle); *handle=NULL;}
  return status ? status : (*handle ? 0 : -9);
}
int @_jit_execute(const @_jit_backend *backend, void *handle, @_vm *vm) {
  if(!backend || !backend->execute || !handle || !vm) return -9;
  return backend->execute(backend->context,handle,vm);
}
void @_jit_release(const @_jit_backend *backend, void *handle) { if(backend && backend->release && handle) backend->release(backend->context,handle); }
#ifdef VMWEAVE_ENABLE_NATIVE
#include <vmweave/native.h>
static int @_vw_native_jit_compile(void *context, const char *stk, const @_tape *tape, void **out) {
  vmweave_native_instruction *code;
  vmweave_native_program *program=NULL;
  size_t i,j; int status;
  if(!out) return -1;
  *out=NULL; status=@_tape_validate(tape); if(status) return status;
  if(tape->size>SIZE_MAX/sizeof(*code)) return -3;
  code=(vmweave_native_instruction *)calloc(tape->size ? tape->size : 1,sizeof(*code));
  if(!code) return -8;
  for(i=0;i<tape->size;++i) {
    code[i].opcode=tape->data[i].opcode; code[i].operand_count=(uint32_t)tape->data[i].operand_count;
    for(j=0;j<tape->data[i].operand_count;++j) code[i].operands[j]=(uint64_t)tape->data[i].operands[j];
  }
  status=vmweave_native_compile((vmweave_native_context *)context,stk,code,tape->size,&program);
  free(code); *out=program; return status;
}
static int @_vw_native_jit_execute(void *context, void *program, @_vm *vm) {
  return vmweave_native_execute((vmweave_native_context *)context,(vmweave_native_program *)program,vm);
}
static void @_vw_native_jit_release(void *context, void *program) { (void)context; vmweave_native_program_destroy((vmweave_native_program *)program); }
static inline int @_jit_native_bind(const vmweave_native_options *options, vmweave_native_context **context, @_jit_backend *backend) {
  if(!context || !backend) return -1;
  memset(backend,0,sizeof(*backend));
  *context=vmweave_native_context_create(options,sizeof(@_vm),@_vw_abi());
  if(!*context) return -8;
  backend->context=*context; backend->compile=@_vw_native_jit_compile;
  backend->execute=@_vw_native_jit_execute; backend->release=@_vw_native_jit_release;
  return 0;
}
#endif
)C";
  }
  return replace(text,n);
}
std::string rewriting(const Module& m) {
  auto n=m.configuration.name; std::ostringstream o;
  o<<"int "<<n<<"_rewrite("<<n<<"_tape *tape) {\n  size_t i=0,j,depth=0;\n  if(!tape || tape->size>tape->capacity || (tape->size && !tape->data)) return -1;\n";
  o<<"  for(j=0;j<tape->size;++j) { const "<<n<<"_metadata *info="<<n<<"_lookup(tape->data[j].opcode); if("<<n<<"_vw_validate_instruction(&tape->data[j],tape->size)) return -4; if(strcmp(info->flow,\"next\") && (strcmp(info->flow,\"halt\") || j+1!=tape->size)) return -9; if(depth<info->inputs) return -2; depth=depth-info->inputs+info->outputs; if(depth>"<<m.configuration.stack_capacity<<") return -3; }\n";
  o<<"  while(i<tape->size) {\n";
  for(const auto& r:m.configuration.rewrites) {
    o<<"    if(tape->size-i >= "<<r.from.size();
    for(size_t k=0;k<r.from.size();++k) o<<" && tape->data[i+"<<k<<"].opcode=="<<n<<"_opcode_"<<r.from[k];
    o<<") {\n";
    for(size_t k=0;k<r.to.size();++k) o<<"      memset(&tape->data[i+"<<k<<"],0,sizeof(tape->data[0])); tape->data[i+"<<k<<"].opcode="<<n<<"_opcode_"<<r.to[k]<<";\n";
    o<<"      memmove(&tape->data[i+"<<r.to.size()<<"], &tape->data[i+"<<r.from.size()<<"], (tape->size-i-"<<r.from.size()<<")*sizeof(tape->data[0])); tape->size-="<<r.from.size()-r.to.size()<<"; i=0; continue;\n    }\n";
  }
  o<<"    ++i;\n  }\n  return 0;\n}\n"; return o.str();
}
std::map<std::string,std::string> fragments(const Module& m) {
  const auto& s=m.configuration; std::map<std::string,std::string> out;
  for(const auto& c:s.components) {
    std::string body;
    if(c=="insncode") body=handlers(m);
    else if(c=="srtbl" || c=="addrtbl" || c=="insntbl") body=table(m,c);
    else if(c=="dispatch") body=dispatch(m);
    else if(c=="compile") body=compiler(m);
    else if(c=="rewrite") body=rewriting(m);
    else if(c=="opcode") {
      for(const auto& w:m.words) body+="#define "+s.name+"_opcode_"+w.name+" "+std::to_string(w.opcode)+"u\n";
    } else if(c=="token") {
      body="const char *"+s.name+"_token(uint32_t opcode) { const "+s.name+"_metadata *info="+s.name+"_lookup(opcode); return info ? info->name : NULL; }\n";
    } else body=optional(m,c);
    if(auto it=s.subsystem_c.find(c);it!=s.subsystem_c.end()) body+="\n/* User subsystem extension. */\n"+it->second+"\n";
    out[c]=body;
  }
  return out;
}
}
Result<std::string> emit_c(const Module& input) {
  auto checked=checked_module(input); if(!checked) return Result<std::string>::err(checked.error());
  auto parts=fragments(checked.value()); std::string c=header(checked.value());
  for(const auto& name:component_names()) if(parts.contains(name)) c+="\n/* ."+name+" */\n"+parts.at(name);
  return Result<std::string>::ok(std::move(c));
}
Result<Artifacts> generate(const Module& input) {
  auto checked=checked_module(input); if(!checked) return Result<Artifacts>::err(checked.error());
  const auto& m=checked.value(); auto n=m.configuration.name; auto parts=fragments(m); Artifacts a;
  a.files[n+".h"]=header(m); a.files[n+".stk00"]=print_stk(m).value();
  std::string c="/* Generated component assembly. */\n#include \""+n+".h\"\n";
  for(const auto& component:component_names()) if(parts.contains(component)) {
    a.files[n+"."+component]="#include \""+n+".h\"\n"+parts.at(component);
    c+="#include \""+n+"."+component+"\"\n";
  }
  a.files[n+".c"]=std::move(c); return Result<Artifacts>::ok(std::move(a));
}
} // namespace limestone::vmweave
