-- VMWeave: declarative VM generator front-end.
local M = {}
local keywords = {}
for word in ("auto break case char const continue default do double else enum extern float for goto if inline int long register restrict return short signed sizeof static struct switch typedef union unsigned void volatile while _Alignas _Alignof _Atomic _Bool _Complex _Generic _Imaginary _Noreturn _Static_assert _Thread_local"):gmatch("%S+") do
  keywords[word] = true
end
local types = {
  u8="uint8_t", u16="uint16_t", u32="uint32_t", u64="uint64_t",
  i8="int8_t", i16="int16_t", i32="int32_t", i64="int64_t",
  f32="float", f64="double", ptr="void *", size="size_t",
}
local function identifier(name)
  assert(type(name)=="string" and name:match("^[A-Za-z][A-Za-z0-9_]*$") and not keywords[name],
    "expected a non-reserved C identifier")
end
local function names(t)
  local result={} for name in pairs(t) do result[#result+1]=name end
  table.sort(result) return result
end
local function declaration(name, spec, allowed)
  identifier(name)
  assert(type(spec)=="table", "declaration metadata must be a table")
  local result={}
  for key,value in pairs(spec) do
    assert(allowed[key], "unknown declaration attribute: "..tostring(key))
    result[key]=value
  end
  return result
end
function M.vm(name)
  identifier(name)
  local states,instructions={},{}
  local x={name=name}
  function x:state(n, spec)
    assert(self==x, "use vm:state(name, metadata)")
    local s=declaration(n,spec,{type=true,count=true})
    assert(not states[n], "duplicate state: "..n)
    assert(types[s.type], "unknown state type: "..tostring(s.type))
    assert(s.count==nil or (type(s.count)=="number" and s.count>0 and s.count<=2147483647 and s.count%1==0),
      "state count must be a positive integer")
    states[n]=s return self
  end
  function x:instruction(n, spec)
    assert(self==x, "use vm:instruction(name, metadata)")
    local s=declaration(n,spec or {},{body=true})
    assert(not instructions[n], "duplicate instruction: "..n)
    assert(s.body==nil or type(s.body)=="string", "instruction body must be C source text")
    assert(not s.body or not s.body:find("\0",1,true), "instruction body contains a NUL byte")
    instructions[n]=s return self
  end
  function x:emit()
    assert(self==x, "use vm:emit()")
    local out={"/* generated by VMWeave: "..name.." */","#include <stdint.h>","#include <stddef.h>","typedef struct "..name.."_vm {"}
    local fields=names(states)
    if #fields==0 then out[#out+1]="  unsigned char unused;" end
    for _,n in ipairs(fields) do local s=states[n]
      out[#out+1]="  "..types[s.type].." "..n..(s.count and "["..string.format("%.0f",s.count).."]" or "")..";"
    end
    out[#out+1]="} "..name.."_vm;"
    for _,n in ipairs(names(instructions)) do local s=instructions[n]
      out[#out+1]="\nvoid "..name.."_"..n.."("..name.."_vm *vm) {"
      out[#out+1]="  (void)vm;"
      if s.body then out[#out+1]=s.body end
      out[#out+1]="}"
    end
    return table.concat(out,"\n").."\n"
  end
  return x
end
return M
