-- VMWeave: declarative VM generator front-end.
local M = {}
local keywords = {}
for word in ("auto break case char const continue default do double else enum extern float for goto if inline int long register restrict return short signed sizeof static struct switch typedef union unsigned void volatile while _Alignas _Alignof _Atomic _Bool _Complex _Generic _Imaginary _Noreturn _Static_assert _Thread_local"):gmatch("%S+") do
  keywords[word] = true
end
local types = {
  u8="uint8_t", u16="uint16_t", u32="uint32_t", u64="uint64_t",
  i8="int8_t", i16="int16_t", i32="int32_t", i64="int64_t",
  f32="float", f64="double", ptr="void *", size="size_t",
}
local function identifier(name)
  assert(type(name)=="string" and name:match("^[A-Za-z][A-Za-z0-9_]*$") and not keywords[name],
    "expected a non-reserved C identifier")
end
local function names(t)
  local result={} for name in pairs(t) do result[#result+1]=name end
  table.sort(result) return result
end
local function declaration(name, spec, allowed)
  identifier(name)
  assert(type(spec)=="table", "declaration metadata must be a table")
  local result={}
  for key,value in pairs(spec) do
    assert(allowed[key], "unknown declaration attribute: "..tostring(key))
    result[key]=value
  end
  return result
end
function M.vm(name)
  identifier(name)
  local states,instructions={},{}
  local x={name=name}
  function x:state(n, spec)
    assert(self==x, "use vm:state(name, metadata)")
    local s=declaration(n,spec,{type=true,count=true})
    assert(not states[n], "duplicate state: "..n)
    assert(types[s.type], "unknown state type: "..tostring(s.type))
    assert(s.count==nil or (type(s.count)=="number" and s.count>0 and s.count<=2147483647 and s.count%1==0),
      "state count must be a positive integer")
    states[n]=s return self
  end
  function x:instruction(n, spec)
    assert(self==x, "use vm:instruction(name, metadata)")
    local s=declaration(n,spec or {},{body=true,opcode=true})
    assert(not instructions[n], "duplicate instruction: "..n)
    assert(s.body==nil or type(s.body)=="string", "instruction body must be C source text")
    assert(not s.body or not s.body:find("\0",1,true), "instruction body contains a NUL byte")
    assert(s.opcode==nil or (type(s.opcode)=="number" and s.opcode>=0 and s.opcode<=2147483647 and s.opcode%1==0), "opcode must be a non-negative 31-bit integer")
    if s.opcode then for _,instruction in pairs(instructions) do assert(instruction.opcode~=s.opcode,"duplicate instruction opcode") end end
    instructions[n]=s return self
  end
  function x:emit(options)
    assert(self==x, "use vm:emit()")
    options=options or {}
    assert(type(options)=="table", "generation configuration must be a table")
    for key in pairs(options) do assert(key=="dispatch" or key=="hooks", "unknown generation option: "..tostring(key)) end
    assert(options.dispatch==nil or options.dispatch=="switch", "unknown dispatch strategy")
    assert(options.hooks==nil or type(options.hooks)=="boolean", "hooks must be Boolean")
    assert(not options.hooks or options.dispatch, "hooks require dispatch")
    local dispatch=options.dispatch=="switch"
    if dispatch then assert(not instructions.step and not instructions.init, "step and init are reserved dispatch handler names") end
    if options.hooks then for _,field in ipairs({"vmweave_userdata","vmweave_before","vmweave_after"}) do assert(not states[field],"state conflicts with runtime hook: "..field) end end
    local out={"/* generated by VMWeave: "..name.." */","#include <stdint.h>","#include <stddef.h>"}
    if options.hooks then out[#out+1]="struct "..name.."_vm;" end
    out[#out+1]="typedef struct "..name.."_vm {"
    local fields=names(states)
    if #fields==0 then out[#out+1]="  unsigned char unused;" end
    for _,n in ipairs(fields) do local s=states[n]
      out[#out+1]="  "..types[s.type].." "..n..(s.count and "["..string.format("%.0f",s.count).."]" or "")..";"
    end
    if options.hooks then
      out[#out+1]="  void *vmweave_userdata;"
      out[#out+1]="  int (*vmweave_before)(struct "..name.."_vm *, uint32_t, void *);"
      out[#out+1]="  void (*vmweave_after)(struct "..name.."_vm *, uint32_t, void *);"
    end
    out[#out+1]="} "..name.."_vm;"
    for _,n in ipairs(names(instructions)) do local s=instructions[n]
      out[#out+1]="\nvoid "..name.."_"..n.."("..name.."_vm *vm) {"
      out[#out+1]="  (void)vm;"
      if s.body then out[#out+1]=s.body end
      out[#out+1]="}"
    end
    if dispatch then
      local used,opcodes={},{}
      for _,n in ipairs(names(instructions)) do if instructions[n].opcode then used[instructions[n].opcode]=true;opcodes[n]=instructions[n].opcode end end
      local next_opcode=0
      for _,n in ipairs(names(instructions)) do if not opcodes[n] then while used[next_opcode] do next_opcode=next_opcode+1 end assert(next_opcode<=2147483647,"opcode space exhausted");opcodes[n]=next_opcode;used[next_opcode]=true end end
      out[#out+1]="\nvoid "..name.."_init("..name.."_vm *vm) { if (vm) { "..name.."_vm zero = {0}; *vm = zero; } }"
      out[#out+1]="\nint "..name.."_step("..name.."_vm *vm, uint32_t opcode) {"
      out[#out+1]="  if (!vm) return -1;"
      -- Validate before invoking hooks so unknown instructions have no effects.
      out[#out+1]="  switch (opcode) {"
      for _,n in ipairs(names(instructions)) do out[#out+1]="    case "..string.format("%.0f",opcodes[n]).."u: break;" end
      out[#out+1]="    default: return -1;\n  }"
      if options.hooks then out[#out+1]="  if (vm->vmweave_before) { int status = vm->vmweave_before(vm, opcode, vm->vmweave_userdata); if (status) return status; }" end
      out[#out+1]="  switch (opcode) {"
      for _,n in ipairs(names(instructions)) do out[#out+1]="    case "..string.format("%.0f",opcodes[n]).."u: "..name.."_"..n.."(vm); break;" end
      out[#out+1]="    default: return -1;\n  }"
      if options.hooks then out[#out+1]="  if (vm->vmweave_after) vm->vmweave_after(vm, opcode, vm->vmweave_userdata);" end
      out[#out+1]="  return 0;\n}"
      for _,n in ipairs(names(instructions)) do out[#out+1]="#define "..name.."_opcode_"..n.." "..string.format("%.0f",opcodes[n]).."u" end
    end
    return table.concat(out,"\n").."\n"
  end
  return x
end
return M
