/* Authoritative ISA grammar. Tables are generated by the vendored DParser. */
Document: Top*;
Top: Arch | Profile | Compiler | Tooling | Regclass | Alias | Encoding | Op | Legacy;
Arch: 'arch' Ident '{' Fields '}';
Profile: 'profile' '{' Fields '}';
Compiler: 'compiler' '{' Fields '}';
Tooling: 'tooling' '{' Fields '}';
Legacy: 'legacy' '{' Fields '}';
Regclass: 'regclass' Ident '{' RegisterEntries '}';
RegisterEntries: RegisterEntry*;
RegisterEntry: Ident '(' Number ')' '=' Number ',';
Alias: 'alias' Ident '=' Value ';';
Encoding: 'encoding' Ident '{' Fields '}';
Op: 'op' Ident '{' Fields '}';
Fields: Field*;
/* Object-valued sections also accept the bundle's brace-terminated spelling. */
Field: FieldName '=' Value? ';' | FieldName '=' Object | FieldName '{' Fields '}' ';'?;
FieldName: Ident ('[' Number ':' Number ']')?;
/* Bare metadata is a fallback: prefer a structured value when both parses exist. */
Value: String | Number | Boolean | Array | Object | SExpr | CallList | BareList -1;
Array: '[' (ArrayValue (',' ArrayValue)*)? ']';
/* A bare comma-list is a field value, never one element of a bracketed array. */
ArrayValue: String | Number | Boolean | Array | Object | SExpr | Call | Ident -1;
Object: '{' Fields '}';
CallList: Call (',' Call)*;
Call: Ident '(' (ArrayValue (',' ArrayValue)*)? ')';
SExpr: '(' SExprItem* ')';
SExprItem: String | Number | Ident | SExpr;
Boolean: 'true' | 'false';
Number: "0x[0-9A-Fa-f]+" | "-?[0-9]+";
BareList: BareAtom (',' BareAtom)*;
BareAtom: "[^;}\]), \"\t\r\n[{(][^;}\]),]*";
String: "\"([^\"\\]|\\[^])*\"";
Ident: "[A-Za-z_][A-Za-z0-9_.-]*";
whitespace: "([ \t\r\n]|#[^\n]*)*";
