/* BURS rule descriptions and explicit selection trees. */
${declare longest_match Document}
Document: Declaration*;
Declaration: RuleSet | Nonterminal | Terminal | Rule | Tree | Include;
RuleSet: 'ruleset' Name '{' RuleDeclaration* '}';
RuleDeclaration: Nonterminal | Terminal | Rule | Include;
Nonterminal: 'nonterminal' Ident ('=' Unsigned)? ';';
Terminal: 'terminal' Ident '(' Unsigned ')' ';';
Rule: 'rule' Unsigned? Ident ':' Pattern '->' Name RuleOption* ';';
RuleOption: Cost | Priority | Type | Immediate | SideEffects | ExternalOnly | Origin | Where;
Where: 'where' Object;
Attribute: Name '=' Value ';' | Name Object ';'?;
Value: String | Integer | Ident | Array | Object;
Array: '[' (Value (',' Value)*)? ']';
Object: '{' Attribute* '}';
Cost: 'cost' Integer;
Priority: 'priority' Integer;
Type: 'type' Ident;
Immediate: 'immediate' '[' Integer '..' Integer ']';
SideEffects: 'side_effects' Boolean;
ExternalOnly: 'external_only' Boolean;
Pattern: Ident PatternArguments? PatternConstraint*;
PatternArguments: '(' (Pattern (',' Pattern)*)? ')';
PatternConstraint: TypeConstraint | ImmediateConstraint | BindingConstraint | RegisterClassConstraint;
TypeConstraint: ':' Ident;
ImmediateConstraint: '[' Integer '..' Integer ']';
BindingConstraint: 'binding' Ident;
RegisterClassConstraint: 'register_class' Ident;
Tree: 'tree' Name '{' TreeNode* Root '}';
TreeNode: 'node' Ref '=' Ident '(' (Ref (',' Ref)*)? ')' TypeConstraint? ('immediate' Integer)? NodeProperty* ';';
NodeProperty: NodeClass | Required | ProducesValue | SideEffect | MayTrap | Call | Terminator | Origin | KnownConstant;
KnownConstant: 'known_constant' Integer;
NodeClass: 'register_class' Ident;
Required: 'required' Boolean;
ProducesValue: 'produces_value' Boolean;
SideEffect: 'side_effect' Boolean;
MayTrap: 'may_trap' Boolean;
Call: 'call' Boolean;
Terminator: 'terminator' Boolean;
Origin: 'origin' String;
Root: 'root' Ref ':' Ident ';';
Include: 'include' String ';';
Name: Ident | String;
Ref: "%[A-Za-z0-9_][A-Za-z0-9_.-]*";
Unsigned: "[0-9]+";
Integer: "-?[0-9]+";
String: "\"([^\"\\]|\\[^])*\"";
Ident: "[A-Za-z_][A-Za-z0-9_.-]*" $term -1;
Boolean: 'true' | 'false';
whitespace: "([ \t\r\n]|#[^\n]*|[/][/][^\n]*|[/][*]([^*]|[*]+[^*/])*[*]+[/])*";
