/* Machine-independent modules and explicit orchestration descriptions. */
${declare longest_match Document}
Document: Declaration*;
Declaration: Module | Pipeline | Target | Import;
Module: 'module' Name '{' ModuleItem* '}';
ModuleItem: Function | Global | Attribute;
Function: 'function' Name Parameters? TypeAnnotation? '{' FunctionItem* '}';
Parameters: '(' (Parameter (',' Parameter)*)? ')';
Parameter: Ref ':' Type;
FunctionItem: Block | Attribute;
Block: 'block' Name Parameters? '{' Statement* '}';
Statement: Operation | Successor | BlockAttribute;
BlockAttribute: 'attribute' Attribute;
Operation: Results? Ident Operands? TypeAnnotation? Object?;
Results: Ref (',' Ref)* '=';
Operands: Operand (','? Operand)*;
Operand: Ref | Immediate | String | Memory | SymbolRef;
Immediate: '#' Integer;
Memory: '[' Operand (',' Operand)* ']';
SymbolRef: '@' Ident;
Successor: 'successor' SymbolRef;
Global: 'global' SymbolRef TypeAnnotation? '=' Value;
TypeAnnotation: ':' Type;
Type: Ident ('<' Type (',' Type)* '>')?;
Pipeline: 'pipeline' Name '{' PipelineItem* '}';
PipelineItem: Stage | Attribute;
Stage: 'stage' StageKind ('using' Name)? Object?;
StageKind: 'ingest' | 'optimize' | 'select' | 'schedule' | 'allocate' | 'machine-ir' | 'emit';
Target: 'target' Name '{' Attribute* '}';
Import: 'import' String;
Attribute: Name '=' Value | Name Object;
Value: String | Integer | Real | Boolean | Ident | Ref | SymbolRef | Array | Object;
Array: '[' (Value (',' Value)*)? ']';
Object: '{' Attribute* '}';
Name: Ident | String;
Ref: "%[A-Za-z0-9_][A-Za-z0-9_.-]*";
Integer: "-?[0-9]+" | "0x[0-9A-Fa-f]+";
Real: "-?[0-9]+\.[0-9]+([eE][+-]?[0-9]+)?" | "-?[0-9]+[eE][+-]?[0-9]+";
Boolean: 'true' | 'false';
String: "\"([^\"\\]|\\[^])*\"";
Ident: "[A-Za-z_][A-Za-z0-9_.-]*" $term -1;
whitespace: "([ \t\r\n]|;[^\n]*|[/][/][^\n]*|[/][*]([^*]|[*]+[^*/])*[*]+[/])*";
