/* Architecture-neutral machine modules. Semicolons start line comments. */
${declare longest_match Document}
Document: Declaration*;
Declaration: Module | Machine | Import;
Machine: 'machine' Name '{' Attribute* '}';
Module: 'module' Name '{' ModuleItem* '}';
ModuleItem: Function | Global | Attribute;
Function: 'function' Name Parameters? TypeAnnotation? '{' FunctionItem* '}';
Parameters: '(' (Parameter (',' Parameter)*)? ')';
Parameter: Register ':' Type;
FunctionItem: Block | RegisterDeclaration | Attribute;
RegisterDeclaration: 'register' Register ':' Name ('width' Unsigned)?;
Block: 'block' Name Parameters? '{' Statement* '}';
Statement: Operation | Successor | BlockAttribute;
BlockAttribute: 'attribute' Attribute;
Operation: Results? Ident Operands? TypeAnnotation? Object?;
Results: Register (',' Register)* '=';
Operands: Operand (','? Operand)*;
Operand: Register | Immediate | String | Memory | SymbolRef;
Register: Virtual | Physical;
Immediate: '#' Integer;
Memory: '[' Operand (',' Operand)* ']' ('attributes' Object)?;
SymbolRef: '@' Ident;
Successor: 'successor' SymbolRef;
Global: 'global' SymbolRef TypeAnnotation? '=' Value;
TypeAnnotation: ':' Type;
Type: Ident ('<' Type (',' Type)* '>')?;
Import: 'import' String;
Attribute: Name '=' Value | Name Object;
Value: String | Integer | Real | Boolean | Ident | Register | SymbolRef | Array | Object | SExpr;
Array: '[' (Value (',' Value)*)? ']';
Object: '{' Attribute* '}';
SExpr: '(' SExprItem* ')';
SExprItem: String | Integer | Ident | Register | SExpr;
Name: Ident | String;
Virtual: "%[A-Za-z0-9_][A-Za-z0-9_.-]*";
Physical: "\$[A-Za-z0-9_][A-Za-z0-9_.-]*";
Unsigned: "[0-9]+";
Integer: "-?[0-9]+" | "0x[0-9A-Fa-f]+";
Real: "-?[0-9]+\.[0-9]+([eE][+-]?[0-9]+)?" | "-?[0-9]+[eE][+-]?[0-9]+";
Boolean: 'true' | 'false';
String: "\"([^\"\\]|\\[^])*\"";
Ident: "[A-Za-z_][A-Za-z0-9_.-]*" $term -1;
whitespace: "([ \t\r\n]|;[^\n]*|[/][/][^\n]*|[/][*]([^*]|[*]+[^*/])*[*]+[/])*";
