/* Inclusive live intervals and register-transfer/allocation constraints. */
${declare longest_match Document}
Document: Unit*;
Unit: 'regtl' Name '{' Declaration* '}';
Declaration: RegisterClass | RegisterAlias | LiveRange | Clobber | SpillSlot | Function | Attribute;
RegisterClass: 'regclass' Name '=' PhysicalList ';';
PhysicalList: '[' (Physical (',' Physical)*)? ']';
RegisterAlias: 'alias' Physical '=' Physical ';';
LiveRange: 'live' Virtual ':' Name '[' Unsigned ',' Unsigned ']' '{' Constraint* '}' ';'?;
Constraint: Allowed | Forbidden | Fixed | Spillable | Attribute;
Allowed: 'allowed' '=' PhysicalList ';';
Forbidden: 'forbidden' '=' PhysicalList ';';
Fixed: 'fixed' '=' Physical ';';
Spillable: 'spillable' '=' Boolean ';';
Clobber: 'clobber' Unsigned '=' PhysicalList ';';
SpillSlot: 'spill_slot' Name '{' Attribute* '}';
Function: 'function' Name '{' Block* '}';
Block: 'block' Name '{' Transfer* '}';
Transfer: Move | ParallelCopy | Instruction | Successor | Attribute;
Move: 'move' Operand '<-' Operand ';';
ParallelCopy: 'parallel' '{' Move* '}';
Successor: 'successor' Name ';';
Instruction: 'instruction' Name '{' InstructionItem* '}';
InstructionItem: RegisterOperand | Constraint;
RegisterOperand: OperandRole Operand ';';
OperandRole: 'def' | 'use' | 'implicit_def' | 'implicit_use';
Operand: Virtual | Physical | Immediate | Memory | Slot;
Immediate: '#' Integer;
Memory: '[' Operand ']';
Slot: 'slot' '(' Name ')';
Attribute: Name '=' Value ';' | Name Object ';'?;
Value: String | Integer | Real | Boolean | Ident | Virtual | Physical | Array | Object;
Array: '[' (Value (',' Value)*)? ']';
Object: '{' Attribute* '}';
Name: Ident | String;
Virtual: "%[A-Za-z0-9_][A-Za-z0-9_.-]*";
Physical: "\$[A-Za-z0-9_][A-Za-z0-9_.-]*";
Unsigned: "[0-9]+";
Integer: "-?[0-9]+" | "0x[0-9A-Fa-f]+";
Real: "-?[0-9]+([.][0-9]+([eE][+-]?[0-9]+)?|[eE][+-]?[0-9]+)";
Boolean: 'true' | 'false';
String: "\"([^\"\\]|\\[^])*\"";
Ident: "[A-Za-z_][A-Za-z0-9_.-]*" $term -1;
whitespace: "([ \t\r\n]|[/][/][^\n]*|[/][*]([^*]|[*]+[^*/])*[*]+[/])*";
