/* Universal machine descriptions, patterns, and program graphs. */
${declare longest_match Document}
Document: Declaration*;
Declaration: Machine | Program | Include;
Machine: 'machine' Name '{' MachineItem* '}';
MachineItem: RegisterClass | RegisterAlias | Operator | Instruction | Pattern | Attribute;
RegisterClass: 'regclass' Name '=' '[' (Physical (',' Physical)*)? ']' ';';
RegisterAlias: 'alias' Physical '=' Physical ';';
Operator: 'operator' Ident '(' Unsigned ')' ';';
Instruction: 'instruction' Name '{' Attribute* '}';
Pattern: 'pattern' Unsigned? Name ':' TreePattern '->' Name PatternOption* ';';
PatternOption: Cost | SideEffects | Where;
Cost: 'cost' Integer;
SideEffects: 'side_effects' Boolean;
Where: 'where' Object;
TreePattern: BindingPattern | OperatorPattern | Integer;
BindingPattern: Variable TypeConstraint? ImmediateConstraint?;
OperatorPattern: Ident ('(' (TreePattern (',' TreePattern)*)? ')')? TypeConstraint? ImmediateConstraint?;
TypeConstraint: ':' Ident;
ImmediateConstraint: '[' Integer '..' Integer ']';
Program: 'program' Name '{' GraphItem* '}';
GraphItem: Block | NodeDeclaration | Output | Dependency | Attribute;
Block: 'block' Name '{' GraphItem* '}';
NodeDeclaration: 'node' Ref '=' Ident '(' (Argument (',' Argument)*)? ')' TypeConstraint? NodeOption* ';';
Argument: Ref | Integer | String;
NodeOption: Required | SideEffects | ProducesValue;
Required: 'required' Boolean;
ProducesValue: 'produces_value' Boolean;
Output: 'output' Ref (',' Ref)* ';';
Dependency: 'dependency' '{' Attribute* '}';
Include: 'include' String ';';
Attribute: Name '=' Value ';' | Name Object ';'?;
Value: String | Integer | Real | Boolean | Ident | Ref | Physical | Array | Object;
Array: '[' (Value (',' Value)*)? ']';
Object: '{' Attribute* '}';
Name: Ident | String;
Variable: "[?$][A-Za-z_][A-Za-z0-9_.-]*";
Ref: "%[A-Za-z0-9_][A-Za-z0-9_.-]*";
Physical: "\$[A-Za-z0-9_][A-Za-z0-9_.-]*";
Unsigned: "[0-9]+";
Integer: "-?[0-9]+" | "0x[0-9A-Fa-f]+";
Real: "-?[0-9]+\.[0-9]+([eE][+-]?[0-9]+)?" | "-?[0-9]+[eE][+-]?[0-9]+";
Boolean: 'true' | 'false';
String: "\"([^\"\\]|\\[^])*\"";
Ident: "[A-Za-z_][A-Za-z0-9_.-]*" $term -1;
whitespace: "([ \t\r\n]|#[^\n]*|[/][/][^\n]*|[/][*]([^*]|[*]+[^*/])*[*]+[/])*";
