#include "infobank.hpp"
#include "metacode/json.hpp"
#include <filesystem>
#include <fstream>
#include <iostream>
#include <set>

namespace {
namespace fs=std::filesystem;
using namespace limestone;
using Value=metacode::Value;
using Object=Value::Object;
using Array=Value::Array;
template<class T> T checked(Result<T> value) {if(!value)throw std::runtime_error(value.error().message);return std::move(value.value());}
[[noreturn]] void fail(const std::string& message) {throw std::runtime_error(message);}
std::string read(const fs::path& path,size_t limit=16*1024*1024) {
  std::ifstream file(path,std::ios::binary|std::ios::ate);if(!file)fail("cannot read "+path.string());
  auto size=file.tellg();if(size<0||uint64_t(size)>limit)fail("input exceeds byte budget: "+path.string());
  std::string out(static_cast<size_t>(size),'\0');file.seekg(0);if(!file.read(out.data(),out.size()))fail("cannot read "+path.string());return out;
}
const Object& object(const Value& value) {auto p=std::get_if<Object>(&value.data);if(!p)fail("manifest entry must be an object");return *p;}
const Value& field(const Object& fields,const std::string& name) {auto it=fields.find(name);if(it==fields.end())fail("missing manifest field: "+name);return it->second;}
std::string string(const Object& fields,const std::string& name) {auto p=std::get_if<std::string>(&field(fields,name).data);if(!p)fail("manifest field must be a string: "+name);return *p;}
uint64_t number(const Object& fields,const std::string& name) {
  auto& value=field(fields,name);if(auto p=std::get_if<uint64_t>(&value.data))return *p;
  if(auto p=std::get_if<int64_t>(&value.data);p&&*p>=0)return uint64_t(*p);fail("manifest field must be unsigned: "+name);
}
void write(const fs::path& path,const std::string& contents,bool check) {
  if(check){if(read(path)!=contents)fail("generated file is stale: "+path.string());return;}
  // Do not replace an unrelated handwritten file during regeneration.
  if(fs::exists(path)&&path.extension()==".lburg"&&!read(path).starts_with("# Generated by limeburg-generate-specs;"))fail("output is not a generated specification: "+path.string());
  if(fs::exists(path)&&read(path)==contents)return;
  auto temporary=path;temporary+=".tmp";if(fs::exists(temporary))fail("temporary output already exists: "+temporary.string());
  try {
    std::ofstream file(temporary,std::ios::binary);if(!file||!file.write(contents.data(),contents.size()))fail("cannot write "+temporary.string());
    file.close();if(!file)fail("cannot finish "+temporary.string());fs::rename(temporary,path);
  }catch(...){std::error_code error;fs::remove(temporary,error);throw;}
}
struct Output {std::string name,contents;};
void generate_bundle(const fs::path& infobank,const fs::path& directory,bool check) {
  auto manifest_value=checked(metacode::parse_json(read(infobank/"manifest.json",2*1024*1024),"metacode/infobank/manifest.json"));
  const auto& manifest=object(manifest_value);
  if(string(manifest,"format")!="isa-description-bundle"||number(manifest,"version")!=2||string(manifest,"semantic_format")!="s-expression")fail("unsupported Infobank manifest contract");
  auto architectures=std::get_if<Array>(&field(manifest,"architectures").data);if(!architectures||architectures->empty()||architectures->size()>256)fail("manifest needs 1..256 architectures");
  std::vector<Output> outputs;Array coverage_architectures;std::set<std::string> files,names;size_t total_rules=0,total_instructions=0;
  for(auto& value:*architectures) {
    const auto& entry=object(value);fs::path source=string(entry,"file");
    if(source.empty()||source.is_absolute()||source.extension()!=".isa")fail("invalid manifest ISA path");
    for(auto& part:source)if(part==".."||part==".")fail("manifest ISA path must be canonical and relative");
    auto filename=source.stem().string()+".lburg";if(!files.insert(filename).second)fail("duplicate specification filename: "+filename);
    auto architecture=checked(metacode::parse_isa(read(infobank/source),"metacode/infobank/"+source.generic_string()));
    if(!names.insert(architecture.name).second)fail("duplicate architecture identity: "+architecture.name);
    if(architecture.name!=string(entry,"arch")||architecture.family!=string(entry,"family")||architecture.model!=string(entry,"model")||architecture.version!=string(entry,"version")||architecture.operations.size()!=number(entry,"instruction_count"))fail("manifest/ISA identity or count mismatch: "+source.string());
    auto& semantics=object(field(entry,"semantics"));if(string(semantics,"format")!="s-expression"||string(semantics,"field")!="semantics"||number(semantics,"count")!=architecture.operations.size())fail("manifest semantic inventory mismatch: "+source.string());
    auto expected_classes=std::get_if<Array>(&field(entry,"register_classes").data);if(!expected_classes)fail("manifest register classes must be an array");
    std::set<std::string> classes,actual;for(auto& klass:*expected_classes){auto p=std::get_if<std::string>(&klass.data);if(!p||!classes.insert(*p).second)fail("invalid/duplicate manifest register class");}
    auto normalized=checked(unisel::from_metacode(architecture));for(auto& [name,members]:normalized.register_classes)actual.insert(name);
    if(actual!=classes)fail("manifest register-class mismatch: "+source.string());
    auto specification=checked(limeburg::from_infobank(architecture));auto contents=checked(limeburg::print_infobank_spec(specification));
    // Exercise the actual GLR loader and canonical round trip before writing.
    auto loaded=checked(limeburg::load_rules(contents,filename));auto canonical=checked(limeburg::print_rules(loaded));
    if(checked(limeburg::print_rules(checked(limeburg::load_rules(canonical,filename))))!=canonical)fail("rule serialization is not reproducible: "+filename);
    outputs.push_back({filename,std::move(contents)});Array instructions;size_t supported=0;
    for(auto& item:specification.coverage) {
      Object record{{"instruction",Value(item.instruction)},{"mode",Value(item.mode)}};
      if(item.rule) {
        ++supported;record["rule"]=Value(int64_t(*item.rule));
        if(item.mode=="inventory")record["source_node"]=Value(Object{{"produces_value",Value(item.produces_value)},{"side_effect",Value(item.side_effect)},{"call",Value(item.call)},{"terminator",Value(item.terminator)},{"may_trap",Value(item.may_trap)},{"register_class",Value(item.register_class)}});
      }else record["reason"]=Value(item.reason);
      instructions.emplace_back(std::move(record));
    }
    auto count=architecture.operations.size();total_rules+=supported;total_instructions+=count;
    coverage_architectures.emplace_back(Object{{"arch",Value(architecture.name)},{"source",Value(source.generic_string())},{"specification",Value(filename)},
      {"instruction_count",Value(int64_t(count))},{"instruction_rules",Value(int64_t(supported))},{"unsupported",Value(int64_t(count-supported))},{"instructions",Value(std::move(instructions))}});
  }
  files.insert("coverage.json");outputs.push_back({"coverage.json",checked(metacode::print_json(Value(Object{{"format",Value(std::string("limeburg-infobank-specs"))},{"version",Value(int64_t(1))},
    {"infobank_version",Value(int64_t(2))},{"cost_model",Value(std::string("instruction_count"))},{"architectures",Value(std::move(coverage_architectures))}})))+"\n"});
  if(fs::exists(directory))for(auto& entry:fs::directory_iterator(directory))if(entry.path().extension()==".lburg"&&!files.contains(entry.path().filename().string()))fail("specification is absent from manifest: "+entry.path().string());
  if(!check)fs::create_directories(directory);
  for(auto& output:outputs)write(directory/output.name,output.contents,check);
  std::cout<<(check?"Verified ":"Generated ")<<architectures->size()<<" specifications: "<<total_rules<<" instruction rules, "<<total_instructions-total_rules<<" explicit coverage boundaries.\n";
}
}
int main(int argc,char** argv) {
  bool check=false;std::vector<std::string> paths;
  for(int k=1;k<argc;++k) {
    std::string argument=argv[k];if(argument=="--check")check=true;
    else if(argument=="--help"){std::cout<<"Usage: limeburg-generate-specs [--check] INFOBANK_DIRECTORY OUTPUT_DIRECTORY\n";return 0;}
    else if(argument.starts_with("--")){std::cerr<<"unknown option: "<<argument<<'\n';return 2;}
    else paths.push_back(std::move(argument));
  }
  if(paths.size()!=2){std::cerr<<"Usage: limeburg-generate-specs [--check] INFOBANK_DIRECTORY OUTPUT_DIRECTORY\n";return 2;}
  try {generate_bundle(paths[0],paths[1],check);return 0;}
  catch(const Error& error){std::cerr<<error.message<<'\n';return 1;}
  catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}
}
