file(MAKE_DIRECTORY "${BINARY}/native-cli")
function(checked)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT status EQUAL 0)
    message(FATAL_ERROR "Native VMWeave command failed: ${ARGV}\n${output}${error}")
  endif()
endfunction()
set(out "${BINARY}/native-cli")
checked("${CLI}" --native --program "${SOURCE}/examples/calculator.tape" -o "${out}" "${SOURCE}/examples/calculator.lua")
file(WRITE "${out}/main.c" "#include \"Calculator.h\"\n#include \"Calculator.h\"\nint main(void) { Calculator_vm vm; Calculator_init(&vm); return Calculator_run_native(&vm,100) || vm.vw_sp!=1 || vm.vw_stack[0]!=30; }\n")
checked("${CC}" -std=c99 -Wall -Wextra -Werror -I "${out}" "${out}/main.c" "${out}/Calculator.so" -o "${out}/main")
checked("${out}/main")
# A saved envelope independently owns the semantics, layout and tape.
checked("${CLI}" --native -o "${out}/reload" "${out}/Calculator.machineir.json")
checked("${CC}" -std=c99 -Wall -Wextra -Werror -I "${out}" "${out}/main.c" "${out}/reload/Calculator.so" -o "${out}/reload-main")
checked("${out}/reload-main")
checked("${CLI}" --emit-assembly --cc "${CC}" --cflag -Wall --cflag -Wextra --cflag -Werror --program "${SOURCE}/examples/calculator.tape" "${out}/Calculator.stk00")
checked("${CLI}" --emit-assembly "${out}/Calculator.machineir.json")
