file(MAKE_DIRECTORY "${BINARY}/runtime")
function(checked)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE result)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "VMWeave command failed (${result}): ${ARGV}")
  endif()
endfunction()
checked("${CLI}" --generate -o "${BINARY}/runtime" "${SOURCE}/examples/calculator.lua")
checked("${CC}" -std=c99 -Wall -Wextra -Werror -I "${BINARY}/runtime" "${SOURCE}/tests/calculator.c" -o "${BINARY}/runtime/calculator")
checked("${BINARY}/runtime/calculator")
checked("${CC}" -std=c99 -Wall -Wextra -Werror -DSEPARATE -I "${BINARY}/runtime" "${SOURCE}/tests/calculator.c" "${BINARY}/runtime/Calculator.c" -o "${BINARY}/runtime/calculator-separate")
checked("${BINARY}/runtime/calculator-separate")
checked("${CLI}" --generate -o "${BINARY}/runtime" "${SOURCE}/examples/objectvm.lua")
checked("${CC}" -std=c99 -Wall -Wextra -Werror -I "${BINARY}/runtime" "${SOURCE}/tests/objectvm.c" -o "${BINARY}/runtime/objectvm")
checked("${BINARY}/runtime/objectvm")
checked("${CC}" -std=c99 -Wall -Wextra -Werror -I "${BINARY}/runtime" -I "${SOURCE}/.." -I "${SOURCE}/../third_party/klib" "${SOURCE}/tests/kalloc.c" "${SOURCE}/../third_party/klib/kalloc.c" -o "${BINARY}/runtime/kalloc")
checked("${BINARY}/runtime/kalloc")
checked("${CLI}" --generate -o "${BINARY}/runtime" "${SOURCE}/tests/cell_state.lua")
checked("${CC}" -std=c99 -Wall -Wextra -Werror -I "${BINARY}/runtime" "${SOURCE}/tests/cell_state.c" -o "${BINARY}/runtime/cell-state")
checked("${BINARY}/runtime/cell-state")
foreach(mode IN ITEMS subroutine indirect direct)
  if(mode STREQUAL "subroutine")
    set(table srtbl)
  elseif(mode STREQUAL "indirect")
    set(table addrtbl)
  else()
    set(table insntbl)
  endif()
  # Reuse the authoritative calculator semantics for every execution strategy.
  file(WRITE "${BINARY}/runtime/${mode}.lua" "local m=dofile([==[${SOURCE}/examples/calculator.lua]==]); m.execution='${mode}'; m.components={'insncode','dispatch','compile','tape','${table}'}; return m\n")
  checked("${CLI}" --generate -o "${BINARY}/runtime/${mode}" "${BINARY}/runtime/${mode}.lua")
  set(definition)
  if(mode STREQUAL "direct")
    set(definition -DDIRECT)
  endif()
  checked("${CC}" -std=c99 -Wall -Wextra -Werror ${definition} -I "${BINARY}/runtime/${mode}" "${SOURCE}/tests/calculator.c" -o "${BINARY}/runtime/${mode}/test")
  checked("${BINARY}/runtime/${mode}/test")
endforeach()
file(WRITE "${BINARY}/runtime/unsigned.lua" "local m=dofile([==[${SOURCE}/examples/calculator.lua]==]); m.stack.cell='uint64_t'; local ins={}; for _,i in ipairs(m.instructions) do if i.name~='DIV' then ins[#ins+1]=i end end; m.instructions=ins; return m\n")
checked("${CLI}" --generate -o "${BINARY}/runtime/unsigned" "${BINARY}/runtime/unsigned.lua")
checked("${CC}" -std=c99 -Wall -Wextra -Werror -I "${BINARY}/runtime/unsigned" "${SOURCE}/tests/unsigned.c" -o "${BINARY}/runtime/unsigned/test")
checked("${BINARY}/runtime/unsigned/test")
# Parsing and regenerating the serialized intermediate must produce identical C.
execute_process(COMMAND "${CLI}" --emit-c "${BINARY}/runtime/Calculator.stk00" OUTPUT_FILE "${BINARY}/runtime/from-stk.c" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "STK-00 lowering failed")
endif()
execute_process(COMMAND "${CLI}" --emit-c "${SOURCE}/examples/calculator.lua" OUTPUT_FILE "${BINARY}/runtime/from-lua.c" RESULT_VARIABLE result)
checked("${CMAKE_COMMAND}" -E compare_files "${BINARY}/runtime/from-stk.c" "${BINARY}/runtime/from-lua.c")
