#include "text.hpp"
#include "parsers/schedrow_ast.hpp"
#include "parsers/semantic.hpp"
#include <charconv>
#include <cmath>
#include <set>

namespace limestone::schedrow {
namespace {
namespace ast=syntax::schedrow;
namespace sem=syntax::semantic;
using Object=sem::Object;using Value=sem::Value;
double real(const std::string& text) {double n=0;auto [end,e]=std::from_chars(text.data(),text.data()+text.size(),n);if(e!=std::errc{}||end!=text.data()+text.size()||!std::isfinite(n)||n<=0)sem::fail("expected positive scheduling quantity: "+text);return n;}
std::string real_text(double n){char bytes[64];auto [end,e]=std::to_chars(bytes,bytes+sizeof(bytes),n);if(e!=std::errc{})sem::fail("unrepresentable scheduling quantity");return std::string(bytes,end);}
std::vector<uint32_t> numbers(const Value& value){std::vector<uint32_t> out;for(auto& v:sem::array(value))out.push_back(sem::number(v.text()));return out;}
Value ids(std::span<const uint32_t> values){Value::Array out;for(auto v:values)out.emplace_back(uint64_t(v));return Value(std::move(out));}
const std::vector<std::string> flows{"none","branch","conditional_branch","return","indirect_branch","trap","call"},orderings{"relaxed","acquire","release","acq_rel","seq_cst"},kinds{"true","anti","output","memory","control","ordering"};
const std::vector<std::string> group_kinds{"ordered","adjacent","same_cycle","bundle","atomic","fusion","pair"};
template<class E> E enumeration(std::string text,const std::vector<std::string>& names){auto i=std::find(names.begin(),names.end(),text);if(i==names.end())sem::fail("unknown scheduling classification: "+text);return static_cast<E>(i-names.begin());}
template<class E> std::string enum_name(E value,const std::vector<std::string>& names){auto n=static_cast<size_t>(value);if(n>=names.size())sem::fail("invalid scheduling classification");return names[n];}
void flag(const Object& fields,const std::string& name,bool& value){if(fields.contains(name))value=sem::boolean(fields.at(name).text());}
void add_names(const Object& fields,const std::string& key,std::set<std::string>& values){if(fields.contains(key))for(auto& v:sem::array(fields.at(key)))values.insert(v.text());}
uint32_t reference(const Value& value,const sem::Names& names){auto text=value.text();if(names.ids.contains(text))return names.at(text);if(!text.starts_with('%')&&names.ids.contains("%"+text))return names.at("%"+text);sem::fail("unknown scheduling reference: "+text,Error::Code::NotFound);}
std::vector<uint32_t> references(const Value& value,const sem::Names& names){std::vector<uint32_t> result;for(auto& v:sem::array(value))result.push_back(reference(v,names));return result;}
void instruction_model(Instruction& i,const Object& fields,const sem::Names& values,const sem::Names& blocks,const sem::Names& physical) {
  auto latency=fields.find("latency");if(latency==fields.end())sem::fail("instruction needs explicit latency or opcode timing: "+i.opcode,Error::Code::Unsupported);
  if(auto object=std::get_if<Object>(&latency->second.data)){if(!object->contains("result")||object->size()!=1)sem::fail("operand/range latency needs an explicit timing adapter",Error::Code::Unsupported);i.latency=sem::number(object->at("result").text());}else i.latency=sem::number(latency->second.text());
  if(fields.contains("throughput"))i.throughput=real(fields.at("throughput").text());
  i.opcode_class=sem::text(fields,"opcode_class");i.semantic_class=sem::text(fields,"semantic_class");i.origin=sem::text(fields,"origin",i.origin);
  flag(fields,"barrier",i.barrier);flag(fields,"call",i.call);flag(fields,"terminator",i.terminator);flag(fields,"may_trap",i.may_trap);flag(fields,"speculative",i.speculative);
  if(fields.contains("issue_slots"))i.issue_slots=numbers(fields.at("issue_slots"));if(fields.contains("priority"))i.priority=sem::small_integer(fields.at("priority").text());
  if(fields.contains("issue")){auto& issue=sem::object(fields.at("issue"));if(fields.contains("issue_slots")&&issue.contains("slots"))sem::fail("duplicate instruction issue-slot contract");if(issue.contains("width")&&sem::number(issue.at("width").text())!=1)sem::fail("multi-slot instructions require an issue adapter",Error::Code::Unsupported);if(issue.contains("slots")){i.issue_slots=numbers(issue.at("slots"));if(i.issue_slots.empty())sem::fail("empty instruction issue-slot set",Error::Code::Unsatisfiable);}for(auto& [key,v]:issue)if(key!="slots"&&key!="width")sem::fail("unknown instruction issue field: "+key,Error::Code::Unsupported);}
  if(fields.contains("block")){if(blocks.ids.empty()){i.block=sem::number(fields.at("block").text());if(i.block)sem::fail("nonzero block requires an explicit CFG");}else i.block=reference(fields.at("block"),blocks);}
  if(fields.contains("block_targets"))i.block_targets=references(fields.at("block_targets"),blocks);
  if(fields.contains("control_flow")){i.control=enumeration<ControlFlow>(fields.at("control_flow").text(),flows);i.call|=i.control==ControlFlow::Call;i.terminator|=i.control!=ControlFlow::None&&i.control!=ControlFlow::Call;}
  if(fields.contains("early_defs"))i.early_defs=references(fields.at("early_defs"),values);
  if(fields.contains("ties"))for(auto& t:sem::array(fields.at("ties"))){auto& pair=sem::array(t);if(pair.size()!=2)sem::fail("scheduling tie needs two values");i.ties.emplace_back(reference(pair[0],values),reference(pair[1],values));}
  if(fields.contains("immediates"))for(auto& v:sem::array(fields.at("immediates"))){auto& item=sem::object(v);i.immediates.emplace_back(reference(sem::required(item,"value"),values),sem::integer(sem::required(item,"integer").text()));}
  if(fields.contains("register_classes"))for(auto& [key,v]:sem::object(fields.at("register_classes")))i.register_classes[reference(Value(key),values)]=v.text();
  if(fields.contains("result_latency"))for(auto& [key,v]:sem::object(fields.at("result_latency")))i.result_latency[reference(Value(key),values)]=sem::number(v.text());
  if(fields.contains("implicit_result_latency"))for(auto& [key,v]:sem::object(fields.at("implicit_result_latency")))i.implicit_result_latency[reference(Value(key),physical)]=sem::number(v.text());
  if(fields.contains("pressure_delta"))for(auto& [key,v]:sem::object(fields.at("pressure_delta")))i.pressure_delta[key]=sem::small_integer(v.text());
  if(fields.contains("effects")){auto& effects=sem::object(fields.at("effects"));flag(effects,"may_trap",i.may_trap);flag(effects,"call",i.call);flag(effects,"barrier",i.barrier);for(auto& [key,v]:effects)if(key!="may_trap"&&key!="call"&&key!="barrier")sem::fail("unsupported scheduling effect: "+key,Error::Code::Unsupported);}
  const Value* access=nullptr;if(fields.contains("access"))access=&fields.at("access");if(fields.contains("memory")){if(std::holds_alternative<Object>(fields.at("memory").data)){if(access)sem::fail("memory and access describe the same effect twice");access=&fields.at("memory");}else flag(fields,"memory",i.memory);}
  if(access){auto& fields=sem::object(*access);MemoryAccess memory;flag(fields,"read",memory.read);flag(fields,"write",memory.write);flag(fields,"volatile",memory.volatile_access);flag(fields,"atomic",memory.atomic);memory.address_space=sem::text(fields,"address_space");memory.ordering=enumeration<MemoryOrdering>(sem::text(fields,"ordering","relaxed"),orderings);if(fields.contains("size"))memory.size=sem::number(fields.at("size").text());if(fields.contains("alignment"))memory.alignment=sem::number(fields.at("alignment").text());if(fields.contains("alias_sets"))memory.alias_sets=numbers(fields.at("alias_sets"));for(auto& [key,v]:fields)if(key!="read"&&key!="write"&&key!="volatile"&&key!="atomic"&&key!="address_space"&&key!="ordering"&&key!="size"&&key!="alignment"&&key!="alias_sets")sem::fail("unsupported memory contract: "+key,Error::Code::Unsupported);i.access=std::move(memory);i.memory=true;}
  if(fields.contains("resources")){auto reservation=[&](const Object& r){ResourceUse use;use.resource=sem::text(r,"resource");if(r.contains("duration"))use.duration=sem::number(r.at("duration").text());if(r.contains("offset"))use.offset=sem::number(r.at("offset").text());if(r.contains("quantity"))use.quantity=real(r.at("quantity").text());if(r.contains("alternatives"))for(auto& v:sem::array(r.at("alternatives")))use.alternatives.push_back(v.text());if(use.resource.empty()&&use.alternatives.empty())sem::fail("empty resource reservation");i.resources.push_back(std::move(use));};auto& resources=fields.at("resources");if(auto array=std::get_if<Value::Array>(&resources.data))for(auto& r:*array)reservation(sem::object(r));else {auto& r=sem::object(resources);if(r.contains("any_of")){ResourceUse use;for(auto& [key,v]:sem::object(r.at("any_of")))if(sem::boolean(v.text()))use.alternatives.push_back(key);if(use.alternatives.empty())sem::fail("empty resource alternatives");i.resources.push_back(std::move(use));}else reservation(r);}}
  for(auto key:{"fusion","speculation","motion","latencies","register_bank"})if(fields.contains(key))sem::fail("scheduling field needs an explicit adapter: "+std::string(key),Error::Code::Unsupported);
}
}
Result<SchedulingDocument> load_schedrow(std::string_view source,std::string_view file) {
  auto parsed=ast::parse(source,file);if(!parsed)return Result<SchedulingDocument>::err(parsed.error());
  try {
    SchedulingDocument document;std::vector<const ast::Region*> regions;std::vector<const ast::Instruction*> standalone;std::vector<const ast::Bundle*> standalone_bundles;
    for(auto& d:parsed.value()->declarations)std::visit([&](const auto& p){using T=std::remove_cvref_t<decltype(*p)>;
      if constexpr(std::is_same_v<T,ast::MachineModel>){if(!document.machine_name.empty())sem::fail(*p,"multiple machine models require separate documents",Error::Code::Conflict);document.machine_name=sem::spelling(*p->name);document.machine_metadata=sem::attributes(p->attributes);}
      else if constexpr(std::is_same_v<T,ast::Region>)regions.push_back(p.get());
      else if constexpr(std::is_same_v<T,ast::Instruction>)standalone.push_back(p.get());
      else standalone_bundles.push_back(p.get());
    },d->value);
    auto& machine=document.machine_metadata;if(machine.contains("issue")){auto& issue=sem::object(machine.at("issue"));document.machine.issue_width=sem::number(sem::required(issue,"width").text());}if(machine.contains("issue_width"))document.machine.issue_width=sem::number(machine.at("issue_width").text());flag(machine,"critical_path",document.machine.critical_path);
    if(machine.contains("resources"))for(auto& [name,value]:sem::object(machine.at("resources"))){auto n=sem::number(value.text());if(!n)sem::fail("resource capacity must be positive");document.machine.resource_capacity[name]=n;}
    if(machine.contains("register_aliases"))for(auto& v:sem::array(machine.at("register_aliases"))){auto& a=sem::array(v);if(a.size()!=2)sem::fail("register alias needs two physical identities");document.machine.register_aliases.emplace_back(sem::number(a[0].text()),sem::number(a[1].text()));}
    Object timings;if(machine.contains("timing"))timings=sem::object(machine.at("timing"));std::set<std::string> region_names;
    auto region=[&](const ast::Region* syntax,const std::vector<const ast::Instruction*>& external,const std::vector<const ast::Bundle*>& external_bundles){TextRegion text;text.region.name=syntax?sem::spelling(*syntax->name):"standalone";if(!region_names.insert(text.region.name).second)sem::fail("duplicate scheduling region",Error::Code::Conflict);std::vector<const ast::Instruction*> instructions=external;std::vector<const ast::Dependency*> dependencies;
      struct RawGroup {std::string id;Object fields;std::vector<const ast::Instruction*> members;};std::vector<RawGroup> groups;
      auto group_name=[](std::string name){if(name.starts_with('%'))name.erase(0,1);return name;};
      std::function<std::vector<const ast::Instruction*>(const ast::Bundle&)> bundle=[&](const ast::Bundle& input){Object attributes;std::vector<const ast::Instruction*> members;
        for(auto& item:input.items)std::visit([&](const auto& p){using T=std::remove_cvref_t<decltype(*p)>;if constexpr(std::is_same_v<T,ast::Instruction>){instructions.push_back(p.get());members.push_back(p.get());}else if constexpr(std::is_same_v<T,ast::Dependency>)dependencies.push_back(p.get());else if constexpr(std::is_same_v<T,ast::Attribute>){if(!attributes.emplace(sem::spelling(*p->name),sem::attribute(*p)).second)sem::fail(*p,"duplicate bundle field",Error::Code::Conflict);}else {auto nested=bundle(*p);members.insert(members.end(),nested.begin(),nested.end());}},item->value);
        auto name=sem::spelling(*input.name);auto id=group_name(sem::text(attributes,"id",name));attributes["kind"]=Value(sem::text(attributes,"kind","bundle"));attributes["name"]=Value(sem::text(attributes,"name",name));groups.push_back({id,std::move(attributes),members});return members;
      };
      if(syntax)for(auto& item:syntax->items)std::visit([&](const auto& p){using T=std::remove_cvref_t<decltype(*p)>;if constexpr(std::is_same_v<T,ast::Instruction>)instructions.push_back(p.get());else if constexpr(std::is_same_v<T,ast::Dependency>)dependencies.push_back(p.get());else if constexpr(std::is_same_v<T,ast::Attribute>){if(!text.metadata.emplace(sem::spelling(*p->name),sem::attribute(*p)).second)sem::fail(*p,"duplicate region field",Error::Code::Conflict);}else bundle(*p);},item->value);
      for(auto input:external_bundles)bundle(*input);
      if(text.metadata.contains("groups"))for(auto& v:sem::array(text.metadata.at("groups"))){auto fields=sem::object(v);groups.push_back({group_name(sem::required(fields,"id").text()),std::move(fields),{}});}
      std::set<std::string> instruction_names,value_names,physical_names,block_names;std::map<const ast::Instruction*,Object> fields;
      if(text.metadata.contains("blocks"))for(auto& v:sem::array(text.metadata.at("blocks"))){auto& b=sem::object(v);auto id=sem::required(b,"id").text();if(!block_names.insert(id).second)sem::fail("duplicate scheduling block",Error::Code::Conflict);BasicBlock block{sem::number(id),sem::text(b,"name")};if(b.contains("successors"))block.successors=numbers(b.at("successors"));if(b.contains("live_out"))for(auto& value:sem::array(b.at("live_out")))value_names.insert(value.text());text.region.blocks.push_back(std::move(block));}
      sem::Names block_ids;block_ids.assign(block_names);if(text.metadata.contains("entry"))text.region.entry=reference(text.metadata.at("entry"),block_ids);else if(!text.region.blocks.empty())text.region.entry=text.region.blocks.front().id;
      for(auto p:instructions){auto name=sem::spelling(*p->name);if(!instruction_names.insert(name).second)sem::fail(*p,"duplicate scheduling instruction",Error::Code::Conflict);Object attributes;
        for(auto& item:p->items)std::visit([&](const auto& n){using N=std::remove_cvref_t<decltype(*n)>;if constexpr(std::is_same_v<N,ast::RegisterOperand>){if(n->role->value=="implicit_def"||n->role->value=="implicit_use")physical_names.insert(n->reference->value);else value_names.insert(n->reference->value);}else if(!attributes.emplace(sem::spelling(*n->name),sem::attribute(*n)).second)sem::fail(*n,"duplicate instruction attribute",Error::Code::Conflict);},item->value);
        add_names(attributes,"early_defs",value_names);if(attributes.contains("ties"))for(auto& pair:sem::array(attributes.at("ties")))for(auto& v:sem::array(pair))value_names.insert(v.text());for(auto key:{"result_latency","register_classes"})if(attributes.contains(key))for(auto& [name,v]:sem::object(attributes.at(key)))value_names.insert(name);if(attributes.contains("immediates"))for(auto& value:sem::array(attributes.at("immediates")))value_names.insert(sem::required(sem::object(value),"value").text());fields[p]=std::move(attributes);
      }
      std::map<std::string,size_t> annotations;
      for(auto p:instructions)if(fields.at(p).contains("group")){auto attributes=sem::object(fields.at(p).at("group"));auto id=group_name(sem::required(attributes,"id").text());if(attributes.contains("members"))sem::fail(*p,"instruction group membership is implicit");if(!annotations.contains(id)){annotations[id]=groups.size();groups.push_back({id,attributes,{}});}else {auto& original=groups[annotations.at(id)].fields;if(sem::print(Value(attributes))!=sem::print(Value(original)))sem::fail(*p,"inconsistent instruction group contract",Error::Code::Conflict);}groups[annotations.at(id)].members.push_back(p);}
      // Numeric metadata references and operand spellings share one identity.
      auto canonical=[](std::set<std::string>& names){std::set<std::string> out;for(auto& n:names)out.insert(n.starts_with('%')?n:"%"+n);names=std::move(out);};canonical(value_names);
      sem::Names instruction_ids,values,physical;instruction_ids.assign(instruction_names);values.assign(value_names);physical.assign(physical_names);text.instruction_names=instruction_ids.ids;text.value_names=values.ids;text.physical_names=physical.ids;
      if(text.metadata.contains("blocks")){auto& list=sem::array(text.metadata.at("blocks"));for(size_t k=0;k<list.size();++k){auto& b=sem::object(list[k]);if(b.contains("live_out"))text.region.blocks[k].live_out=references(b.at("live_out"),values);}}
      for(auto p:instructions){Instruction i{};i.id=instruction_ids.at(sem::spelling(*p->name));i.origin=std::string(file)+":"+std::to_string(p->source.begin.line);auto attributes=fields.at(p);i.opcode=sem::text(attributes,"opcode");if(i.opcode.empty())sem::fail(*p,"instruction has no opcode");if(timings.contains(i.opcode)){auto model=sem::object(timings.at(i.opcode));if(model.contains("group"))sem::fail(*p,"opcode timing cannot declare occurrence-specific groups",Error::Code::Unsupported);for(auto& [key,value]:attributes)model[key]=value;attributes=std::move(model);}text.instruction_metadata[i.id]=attributes;
        for(auto& item:p->items)std::visit([&](const auto& n){using N=std::remove_cvref_t<decltype(*n)>;if constexpr(std::is_same_v<N,ast::RegisterOperand>){auto role=n->role->value;if(role=="implicit_def")i.implicit_defs.push_back(physical.at(n->reference->value));else if(role=="implicit_use")i.implicit_uses.push_back(physical.at(n->reference->value));else if(role=="def")i.defs.push_back(values.at(n->reference->value));else i.uses.push_back(values.at(n->reference->value));}},item->value);
        instruction_model(i,attributes,values,block_ids,physical);text.region.instructions.push_back(std::move(i));
      }
      std::set<std::string> group_names;for(auto& group:groups)if(!group_names.insert(group.id).second)sem::fail("duplicate scheduling group",Error::Code::Conflict);sem::Names group_ids;group_ids.assign(group_names);
      for(auto& raw:groups){auto& fields=raw.fields;InstructionGroup group{group_ids.at(raw.id),enumeration<GroupKind>(sem::text(fields,"kind","ordered"),group_kinds)};group.name=sem::text(fields,"name",raw.id);group.origin=sem::text(fields,"origin",std::string(file));group.pattern=sem::text(fields,"pattern");if(fields.contains("benefit"))group.benefit=sem::small_integer(fields.at("benefit").text());if(fields.contains("members"))group.members=references(fields.at("members"),instruction_ids);else for(auto p:raw.members)group.members.push_back(instruction_ids.at(sem::spelling(*p->name)));
        if(fields.contains("issue")){auto& issue=sem::object(fields.at("issue"));if(issue.contains("width")){group.issue_width=sem::number(issue.at("width").text());if(!group.issue_width)sem::fail("zero group issue width");}if(issue.contains("slots")){group.issue_slots=numbers(issue.at("slots"));if(group.issue_slots.empty())sem::fail("empty group issue-slot set",Error::Code::Unsatisfiable);}for(auto& [key,v]:issue)if(key!="width"&&key!="slots")sem::fail("unknown group issue field: "+key,Error::Code::Unsupported);}
        for(auto& [key,v]:fields)if(key!="id"&&key!="kind"&&key!="members"&&key!="name"&&key!="origin"&&key!="pattern"&&key!="benefit"&&key!="issue")sem::fail("unknown group field: "+key,Error::Code::Unsupported);text.region.groups.push_back(std::move(group));
      }
      for(auto p:dependencies){auto fields=sem::attributes(p->attributes);Dependency d{instruction_ids.at(sem::required(fields,"producer").text()),instruction_ids.at(sem::required(fields,"consumer").text()),enumeration<DepKind>(sem::required(fields,"kind").text(),kinds)};if(fields.contains("latency"))d.latency=sem::number(fields.at("latency").text());if(fields.contains("distance"))d.distance=sem::number(fields.at("distance").text());if(fields.contains("scheduler_only"))d.scheduler_only=sem::boolean(fields.at("scheduler_only").text());for(auto& [key,v]:fields)if(key!="producer"&&key!="consumer"&&key!="kind"&&key!="latency"&&key!="distance"&&key!="scheduler_only")sem::fail(*p,"unsupported dependency property: "+key,Error::Code::Unsupported);text.region.deps.push_back(d);}
      auto checked=schedrow::dependencies(text.region,document.machine.register_aliases);if(!checked)throw checked.error();document.regions.push_back(std::move(text));
    };
    for(auto p:regions)region(p,{},{});if(!standalone.empty()||!standalone_bundles.empty())region(nullptr,standalone,standalone_bundles);
    return Result<SchedulingDocument>::ok(std::move(document));
  }catch(const Error& e){return Result<SchedulingDocument>::err(e);}
}
Result<std::string> print_schedrow(const SchedulingDocument& document) {
  try {
    std::string out;Object machine=document.machine_metadata;machine.erase("issue");machine.erase("register_aliases");machine["issue_width"]=Value(uint64_t(document.machine.issue_width));machine["critical_path"]=Value(document.machine.critical_path);Object capacities;for(auto& [name,cap]:document.machine.resource_capacity)capacities[name]=Value(uint64_t(cap));machine["resources"]=Value(std::move(capacities));if(!document.machine.register_aliases.empty()){Value::Array aliases;for(auto [a,b]:document.machine.register_aliases)aliases.emplace_back(Value::Array{Value(uint64_t(a)),Value(uint64_t(b))});machine["register_aliases"]=Value(std::move(aliases));}
    out+="machine_model "+sem::quote(document.machine_name.empty()?"machine":document.machine_name)+" "+sem::print(Value(machine))+"\n";
    for(auto& text:document.regions){auto& region=text.region;auto valid=validate_region(region);if(!valid)return Result<std::string>::err(valid.error());out+="region "+sem::quote(region.name)+" {\n";Object metadata=text.metadata;metadata.erase("blocks");metadata.erase("entry");metadata.erase("groups");if(!region.blocks.empty()){Value::Array blocks;for(auto& b:region.blocks)blocks.emplace_back(Object{{"id",Value(uint64_t(b.id))},{"name",Value(b.name)},{"successors",ids(b.successors)},{"live_out",ids(b.live_out)}});metadata["blocks"]=Value(std::move(blocks));metadata["entry"]=Value(uint64_t(region.entry));}
      if(!region.groups.empty()){Value::Array groups;for(auto& g:region.groups){Object fields{{"id",Value(uint64_t(g.id))},{"kind",Value(enum_name(g.kind,group_kinds))},{"members",ids(g.members)},{"name",Value(g.name)},{"origin",Value(g.origin)},{"pattern",Value(g.pattern)},{"benefit",Value(int64_t(g.benefit))}};if(g.issue_width||!g.issue_slots.empty()){Object issue;if(g.issue_width)issue["width"]=Value(uint64_t(g.issue_width));if(!g.issue_slots.empty())issue["slots"]=ids(g.issue_slots);fields["issue"]=Value(std::move(issue));}groups.emplace_back(std::move(fields));}metadata["groups"]=Value(std::move(groups));}for(auto& [key,v]:sem::ordered(metadata))out+="  "+sem::quote(key)+" = "+sem::print(v)+";\n";
      for(auto& i:region.instructions){Object fields=text.instruction_metadata.contains(i.id)?text.instruction_metadata.at(i.id):Object{};fields.erase("effects");fields.erase("access");fields["opcode"]=Value(i.opcode);fields["latency"]=Value(uint64_t(i.latency));fields["throughput"]=Value(real_text(i.throughput));fields["origin"]=Value(i.origin);fields["opcode_class"]=Value(i.opcode_class);fields["semantic_class"]=Value(i.semantic_class);fields["barrier"]=Value(i.barrier);fields["call"]=Value(i.call);fields["terminator"]=Value(i.terminator);fields["may_trap"]=Value(i.may_trap);fields["speculative"]=Value(i.speculative);fields["memory"]=Value(i.memory);fields["issue_slots"]=ids(i.issue_slots);fields["priority"]=Value(int64_t(i.priority));fields["early_defs"]=ids(i.early_defs);fields["block"]=Value(uint64_t(i.block));fields["block_targets"]=ids(i.block_targets);fields["control_flow"]=Value(enum_name(i.control,flows));Value::Array immediates,ties,resources;Object latencies,classes,pressure;
        fields.erase("group");fields.erase("issue");Object implicit_latencies;for(auto [v,n]:i.implicit_result_latency)implicit_latencies[std::to_string(v)]=Value(uint64_t(n));fields["implicit_result_latency"]=Value(std::move(implicit_latencies));
        for(auto [v,n]:i.immediates)immediates.emplace_back(Object{{"value",Value(uint64_t(v))},{"integer",Value(n)}});fields["immediates"]=Value(std::move(immediates));for(auto [a,b]:i.ties)ties.emplace_back(Value::Array{Value(uint64_t(a)),Value(uint64_t(b))});fields["ties"]=Value(std::move(ties));for(auto& [v,n]:i.result_latency)latencies[std::to_string(v)]=Value(uint64_t(n));fields["result_latency"]=Value(std::move(latencies));for(auto& [v,c]:i.register_classes)classes[std::to_string(v)]=Value(c);fields["register_classes"]=Value(std::move(classes));for(auto& [c,n]:i.pressure_delta)pressure[c]=Value(int64_t(n));fields["pressure_delta"]=Value(std::move(pressure));
        for(auto& r:i.resources){Value::Array alternatives;for(auto& name:r.alternatives)alternatives.emplace_back(name);resources.emplace_back(Object{{"resource",Value(r.resource)},{"duration",Value(uint64_t(r.duration))},{"offset",Value(uint64_t(r.offset))},{"quantity",Value(real_text(r.quantity))},{"alternatives",Value(std::move(alternatives))}});}fields["resources"]=Value(std::move(resources));if(i.access){auto& a=*i.access;fields["access"]=Value(Object{{"read",Value(a.read)},{"write",Value(a.write)},{"volatile",Value(a.volatile_access)},{"atomic",Value(a.atomic)},{"ordering",Value(enum_name(a.ordering,orderings))},{"address_space",Value(a.address_space)},{"size",Value(uint64_t(a.size))},{"alignment",Value(uint64_t(a.alignment))},{"alias_sets",ids(a.alias_sets)}});}
        out+="  instruction %"+std::to_string(i.id)+" {\n";for(auto v:i.defs)out+="    def %"+std::to_string(v)+";\n";for(auto v:i.uses)out+="    use %"+std::to_string(v)+";\n";for(auto v:i.implicit_defs)out+="    implicit_def %"+std::to_string(v)+";\n";for(auto v:i.implicit_uses)out+="    implicit_use %"+std::to_string(v)+";\n";for(auto& [key,v]:sem::ordered(fields))out+="    "+sem::quote(key)+" = "+sem::print(v)+";\n";out+="  }\n";
      }
      for(auto& d:region.deps)out+="  dependency { producer = %"+std::to_string(d.producer)+"; consumer = %"+std::to_string(d.consumer)+"; kind = "+sem::quote(enum_name(d.kind,kinds))+"; latency = "+std::to_string(d.latency)+"; distance = "+std::to_string(d.distance)+"; scheduler_only = "+std::string(d.scheduler_only?"true":"false")+"; }\n";
      out+="}\n";
    }
    return Result<std::string>::ok(std::move(out));
  }catch(const Error& e){return Result<std::string>::err(e);}
}
}
